// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package welcomer

import (
	"errors"
	"fmt"
)

const (
	// GuildFeatureCustomWelcomerImageBuilder is a GuildFeature of type CustomWelcomerImageBuilder.
	GuildFeatureCustomWelcomerImageBuilder GuildFeature = "CustomWelcomerImageBuilder"
)

var ErrInvalidGuildFeature = errors.New("not a valid GuildFeature")

// String implements the Stringer interface.
func (x GuildFeature) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x GuildFeature) IsValid() bool {
	_, err := ParseGuildFeature(string(x))
	return err == nil
}

var _GuildFeatureValue = map[string]GuildFeature{
	"CustomWelcomerImageBuilder": GuildFeatureCustomWelcomerImageBuilder,
}

// ParseGuildFeature attempts to convert a string to a GuildFeature.
func ParseGuildFeature(name string) (GuildFeature, error) {
	if x, ok := _GuildFeatureValue[name]; ok {
		return x, nil
	}
	return GuildFeature(""), fmt.Errorf("%s is %w", name, ErrInvalidGuildFeature)
}

// MarshalText implements the text marshaller method.
func (x GuildFeature) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *GuildFeature) UnmarshalText(text []byte) error {
	tmp, err := ParseGuildFeature(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *GuildFeature) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
