// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package welcomer

import (
	"errors"
	"fmt"
)

const (
	// IngestMessageEventTypeCreate is a IngestMessageEventType of type Create.
	IngestMessageEventTypeCreate IngestMessageEventType = iota
	// IngestMessageEventTypeEdit is a IngestMessageEventType of type Edit.
	IngestMessageEventTypeEdit
)

var ErrInvalidIngestMessageEventType = errors.New("not a valid IngestMessageEventType")

const _IngestMessageEventTypeName = "createedit"

var _IngestMessageEventTypeMap = map[IngestMessageEventType]string{
	IngestMessageEventTypeCreate: _IngestMessageEventTypeName[0:6],
	IngestMessageEventTypeEdit:   _IngestMessageEventTypeName[6:10],
}

// String implements the Stringer interface.
func (x IngestMessageEventType) String() string {
	if str, ok := _IngestMessageEventTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("IngestMessageEventType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IngestMessageEventType) IsValid() bool {
	_, ok := _IngestMessageEventTypeMap[x]
	return ok
}

var _IngestMessageEventTypeValue = map[string]IngestMessageEventType{
	_IngestMessageEventTypeName[0:6]:  IngestMessageEventTypeCreate,
	_IngestMessageEventTypeName[6:10]: IngestMessageEventTypeEdit,
}

// ParseIngestMessageEventType attempts to convert a string to a IngestMessageEventType.
func ParseIngestMessageEventType(name string) (IngestMessageEventType, error) {
	if x, ok := _IngestMessageEventTypeValue[name]; ok {
		return x, nil
	}
	return IngestMessageEventType(0), fmt.Errorf("%s is %w", name, ErrInvalidIngestMessageEventType)
}

// MarshalText implements the text marshaller method.
func (x IngestMessageEventType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *IngestMessageEventType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseIngestMessageEventType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *IngestMessageEventType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// IngestVoiceChannelEventTypeJoin is a IngestVoiceChannelEventType of type Join.
	IngestVoiceChannelEventTypeJoin IngestVoiceChannelEventType = iota
	// IngestVoiceChannelEventTypeLeave is a IngestVoiceChannelEventType of type Leave.
	IngestVoiceChannelEventTypeLeave
)

var ErrInvalidIngestVoiceChannelEventType = errors.New("not a valid IngestVoiceChannelEventType")

const _IngestVoiceChannelEventTypeName = "joinleave"

var _IngestVoiceChannelEventTypeMap = map[IngestVoiceChannelEventType]string{
	IngestVoiceChannelEventTypeJoin:  _IngestVoiceChannelEventTypeName[0:4],
	IngestVoiceChannelEventTypeLeave: _IngestVoiceChannelEventTypeName[4:9],
}

// String implements the Stringer interface.
func (x IngestVoiceChannelEventType) String() string {
	if str, ok := _IngestVoiceChannelEventTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("IngestVoiceChannelEventType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IngestVoiceChannelEventType) IsValid() bool {
	_, ok := _IngestVoiceChannelEventTypeMap[x]
	return ok
}

var _IngestVoiceChannelEventTypeValue = map[string]IngestVoiceChannelEventType{
	_IngestVoiceChannelEventTypeName[0:4]: IngestVoiceChannelEventTypeJoin,
	_IngestVoiceChannelEventTypeName[4:9]: IngestVoiceChannelEventTypeLeave,
}

// ParseIngestVoiceChannelEventType attempts to convert a string to a IngestVoiceChannelEventType.
func ParseIngestVoiceChannelEventType(name string) (IngestVoiceChannelEventType, error) {
	if x, ok := _IngestVoiceChannelEventTypeValue[name]; ok {
		return x, nil
	}
	return IngestVoiceChannelEventType(0), fmt.Errorf("%s is %w", name, ErrInvalidIngestVoiceChannelEventType)
}

// MarshalText implements the text marshaller method.
func (x IngestVoiceChannelEventType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *IngestVoiceChannelEventType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseIngestVoiceChannelEventType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *IngestVoiceChannelEventType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
