// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package welcomer

import (
	"errors"
	"fmt"
)

const (
	// PollResubmissionOptionNever is a PollResubmissionOption of type never.
	PollResubmissionOptionNever PollResubmissionOption = "never"
	// PollResubmissionOptionOnlyAdditions is a PollResubmissionOption of type only_additions.
	PollResubmissionOptionOnlyAdditions PollResubmissionOption = "only_additions"
	// PollResubmissionOptionAlways is a PollResubmissionOption of type always.
	PollResubmissionOptionAlways PollResubmissionOption = "always"
)

var ErrInvalidPollResubmissionOption = errors.New("not a valid PollResubmissionOption")

// String implements the Stringer interface.
func (x PollResubmissionOption) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PollResubmissionOption) IsValid() bool {
	_, err := ParsePollResubmissionOption(string(x))
	return err == nil
}

var _PollResubmissionOptionValue = map[string]PollResubmissionOption{
	"never":          PollResubmissionOptionNever,
	"only_additions": PollResubmissionOptionOnlyAdditions,
	"always":         PollResubmissionOptionAlways,
}

// ParsePollResubmissionOption attempts to convert a string to a PollResubmissionOption.
func ParsePollResubmissionOption(name string) (PollResubmissionOption, error) {
	if x, ok := _PollResubmissionOptionValue[name]; ok {
		return x, nil
	}
	return PollResubmissionOption(""), fmt.Errorf("%s is %w", name, ErrInvalidPollResubmissionOption)
}

// MarshalText implements the text marshaller method.
func (x PollResubmissionOption) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PollResubmissionOption) UnmarshalText(text []byte) error {
	tmp, err := ParsePollResubmissionOption(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *PollResubmissionOption) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// PollResultVisibilityOptionAlways is a PollResultVisibilityOption of type always.
	PollResultVisibilityOptionAlways PollResultVisibilityOption = "always"
	// PollResultVisibilityOptionAfterVoting is a PollResultVisibilityOption of type after_voting.
	PollResultVisibilityOptionAfterVoting PollResultVisibilityOption = "after_voting"
	// PollResultVisibilityOptionAfterEnd is a PollResultVisibilityOption of type after_end.
	PollResultVisibilityOptionAfterEnd PollResultVisibilityOption = "after_end"
	// PollResultVisibilityOptionNever is a PollResultVisibilityOption of type never.
	PollResultVisibilityOptionNever PollResultVisibilityOption = "never"
)

var ErrInvalidPollResultVisibilityOption = errors.New("not a valid PollResultVisibilityOption")

// String implements the Stringer interface.
func (x PollResultVisibilityOption) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PollResultVisibilityOption) IsValid() bool {
	_, err := ParsePollResultVisibilityOption(string(x))
	return err == nil
}

var _PollResultVisibilityOptionValue = map[string]PollResultVisibilityOption{
	"always":       PollResultVisibilityOptionAlways,
	"after_voting": PollResultVisibilityOptionAfterVoting,
	"after_end":    PollResultVisibilityOptionAfterEnd,
	"never":        PollResultVisibilityOptionNever,
}

// ParsePollResultVisibilityOption attempts to convert a string to a PollResultVisibilityOption.
func ParsePollResultVisibilityOption(name string) (PollResultVisibilityOption, error) {
	if x, ok := _PollResultVisibilityOptionValue[name]; ok {
		return x, nil
	}
	return PollResultVisibilityOption(""), fmt.Errorf("%s is %w", name, ErrInvalidPollResultVisibilityOption)
}

// MarshalText implements the text marshaller method.
func (x PollResultVisibilityOption) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PollResultVisibilityOption) UnmarshalText(text []byte) error {
	tmp, err := ParsePollResultVisibilityOption(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *PollResultVisibilityOption) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
