// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: guild_welcomer_images_query.sql

package database

import (
	"context"

	"github.com/gofrs/uuid"
)

const CreateGuildWelcomerImage = `-- name: CreateGuildWelcomerImage :one
INSERT INTO guild_welcomer_images (image_uuid, guild_id, created_at, image_format)
    VALUES (uuid_generate_v4 (), $1, now(), $2)
RETURNING
    image_uuid, guild_id, created_at, image_format
`

type CreateGuildWelcomerImageParams struct {
	GuildID     int64 `json:"guild_id"`
	ImageFormat int32 `json:"image_format"`
}

func (q *Queries) CreateGuildWelcomerImage(ctx context.Context, arg *CreateGuildWelcomerImageParams) (*GuildWelcomerImages, error) {
	row := q.db.QueryRow(ctx, CreateGuildWelcomerImage, arg.GuildID, arg.ImageFormat)
	var i GuildWelcomerImages
	err := row.Scan(
		&i.ImageUuid,
		&i.GuildID,
		&i.CreatedAt,
		&i.ImageFormat,
	)
	return &i, err
}

const DeleteGuildWelcomerImage = `-- name: DeleteGuildWelcomerImage :execrows
DELETE FROM guild_welcomer_images
WHERE image_uuid = $1
`

func (q *Queries) DeleteGuildWelcomerImage(ctx context.Context, imageUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteGuildWelcomerImage, imageUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const GetGuildWelcomerImage = `-- name: GetGuildWelcomerImage :one
SELECT
    image_uuid, guild_id, created_at, image_format
FROM
    guild_welcomer_images
WHERE
    image_uuid = $1
`

func (q *Queries) GetGuildWelcomerImage(ctx context.Context, imageUuid uuid.UUID) (*GuildWelcomerImages, error) {
	row := q.db.QueryRow(ctx, GetGuildWelcomerImage, imageUuid)
	var i GuildWelcomerImages
	err := row.Scan(
		&i.ImageUuid,
		&i.GuildID,
		&i.CreatedAt,
		&i.ImageFormat,
	)
	return &i, err
}
