// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: guild_settings_welcomer_images_query.sql

package database

import (
	"context"
	"database/sql"
)

const CreateWelcomerImagesGuildSettings = `-- name: CreateWelcomerImagesGuildSettings :one
INSERT INTO guild_settings_Welcomer_images (guild_id)
    VALUES ($1)
RETURNING
    guild_id, toggle_enabled, toggle_image_border, background_name, colour_text, colour_text_border, colour_image_border, colour_profile_border, image_alignment, image_theme, image_message, image_profile_border_type
`

func (q *Queries) CreateWelcomerImagesGuildSettings(ctx context.Context, guildID int64) (*GuildSettingsWelcomerImages, error) {
	row := q.db.QueryRow(ctx, CreateWelcomerImagesGuildSettings, guildID)
	var i GuildSettingsWelcomerImages
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.ToggleImageBorder,
		&i.BackgroundName,
		&i.ColourText,
		&i.ColourTextBorder,
		&i.ColourImageBorder,
		&i.ColourProfileBorder,
		&i.ImageAlignment,
		&i.ImageTheme,
		&i.ImageMessage,
		&i.ImageProfileBorderType,
	)
	return &i, err
}

const GetWelcomerImagesGuildSettings = `-- name: GetWelcomerImagesGuildSettings :one
SELECT
    guild_id, toggle_enabled, toggle_image_border, background_name, colour_text, colour_text_border, colour_image_border, colour_profile_border, image_alignment, image_theme, image_message, image_profile_border_type
FROM
    guild_settings_Welcomer_images
WHERE
    guild_id = $1
`

func (q *Queries) GetWelcomerImagesGuildSettings(ctx context.Context, guildID int64) (*GuildSettingsWelcomerImages, error) {
	row := q.db.QueryRow(ctx, GetWelcomerImagesGuildSettings, guildID)
	var i GuildSettingsWelcomerImages
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.ToggleImageBorder,
		&i.BackgroundName,
		&i.ColourText,
		&i.ColourTextBorder,
		&i.ColourImageBorder,
		&i.ColourProfileBorder,
		&i.ImageAlignment,
		&i.ImageTheme,
		&i.ImageMessage,
		&i.ImageProfileBorderType,
	)
	return &i, err
}

const UpdateWelcomerImagesGuildSettings = `-- name: UpdateWelcomerImagesGuildSettings :execrows
UPDATE
    guild_settings_Welcomer_images
SET
    toggle_enabled = $2,
    toggle_image_border = $3,
    background_name = $4,
    colour_text = $5,
    colour_text_border = $6,
    colour_image_border = $7,
    colour_profile_border = $8,
    image_alignment = $9,
    image_theme = $10,
    image_message = $11,
    image_profile_border_type = $12
WHERE
    guild_id = $1
`

type UpdateWelcomerImagesGuildSettingsParams struct {
	GuildID                int64          `json:"guild_id"`
	ToggleEnabled          sql.NullBool   `json:"toggle_enabled"`
	ToggleImageBorder      sql.NullBool   `json:"toggle_image_border"`
	BackgroundName         sql.NullString `json:"background_name"`
	ColourText             sql.NullInt32  `json:"colour_text"`
	ColourTextBorder       sql.NullInt32  `json:"colour_text_border"`
	ColourImageBorder      sql.NullInt32  `json:"colour_image_border"`
	ColourProfileBorder    sql.NullInt32  `json:"colour_profile_border"`
	ImageAlignment         sql.NullInt32  `json:"image_alignment"`
	ImageTheme             sql.NullInt32  `json:"image_theme"`
	ImageMessage           sql.NullString `json:"image_message"`
	ImageProfileBorderType sql.NullInt32  `json:"image_profile_border_type"`
}

func (q *Queries) UpdateWelcomerImagesGuildSettings(ctx context.Context, arg *UpdateWelcomerImagesGuildSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, UpdateWelcomerImagesGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.ToggleImageBorder,
		arg.BackgroundName,
		arg.ColourText,
		arg.ColourTextBorder,
		arg.ColourImageBorder,
		arg.ColourProfileBorder,
		arg.ImageAlignment,
		arg.ImageTheme,
		arg.ImageMessage,
		arg.ImageProfileBorderType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
