// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package database

import (
	"errors"
	"fmt"
)

const (
	// AuditTypeUnknown is a AuditType of type Unknown.
	AuditTypeUnknown AuditType = iota
	// AuditTypeBorderwallRequests is a AuditType of type Borderwall_requests.
	AuditTypeBorderwallRequests
	// AuditTypeCustomBots is a AuditType of type Custom_bots.
	AuditTypeCustomBots
	// AuditTypeGuildSettingsAutoroles is a AuditType of type Guild_settings_autoroles.
	AuditTypeGuildSettingsAutoroles
	// AuditTypeGuildSettingsBorderwall is a AuditType of type Guild_settings_borderwall.
	AuditTypeGuildSettingsBorderwall
	// AuditTypeGuildSettingsFreeroles is a AuditType of type Guild_settings_freeroles.
	AuditTypeGuildSettingsFreeroles
	// AuditTypeGuildSettingsLeaver is a AuditType of type Guild_settings_leaver.
	AuditTypeGuildSettingsLeaver
	// AuditTypeGuildSettingsRules is a AuditType of type Guild_settings_rules.
	AuditTypeGuildSettingsRules
	// AuditTypeGuildSettingsTempchannels is a AuditType of type Guild_settings_tempchannels.
	AuditTypeGuildSettingsTempchannels
	// AuditTypeGuildSettingsTimeroles is a AuditType of type Guild_settings_timeroles.
	AuditTypeGuildSettingsTimeroles
	// AuditTypeGuildSettingsWelcomer is a AuditType of type Guild_settings_welcomer.
	AuditTypeGuildSettingsWelcomer
	// AuditTypeGuildSettingsWelcomerDms is a AuditType of type Guild_settings_welcomer_dms.
	AuditTypeGuildSettingsWelcomerDms
	// AuditTypeGuildSettingsWelcomerImages is a AuditType of type Guild_settings_welcomer_images.
	AuditTypeGuildSettingsWelcomerImages
	// AuditTypeGuildSettingsWelcomerText is a AuditType of type Guild_settings_welcomer_text.
	AuditTypeGuildSettingsWelcomerText
	// AuditTypeGuilds is a AuditType of type Guilds.
	AuditTypeGuilds
	// AuditTypeUsers is a AuditType of type Users.
	AuditTypeUsers
	// AuditTypeWelcomerImages is a AuditType of type Welcomer_images.
	AuditTypeWelcomerImages
	// AuditTypeGuildFeatures is a AuditType of type Guild_features.
	AuditTypeGuildFeatures
)

var ErrInvalidAuditType = errors.New("not a valid AuditType")

const _AuditTypeName = "unknownborderwall_requestscustom_botsguild_settings_autorolesguild_settings_borderwallguild_settings_freerolesguild_settings_leaverguild_settings_rulesguild_settings_tempchannelsguild_settings_timerolesguild_settings_welcomerguild_settings_welcomer_dmsguild_settings_welcomer_imagesguild_settings_welcomer_textguildsuserswelcomer_imagesguild_features"

var _AuditTypeMap = map[AuditType]string{
	AuditTypeUnknown:                     _AuditTypeName[0:7],
	AuditTypeBorderwallRequests:          _AuditTypeName[7:26],
	AuditTypeCustomBots:                  _AuditTypeName[26:37],
	AuditTypeGuildSettingsAutoroles:      _AuditTypeName[37:61],
	AuditTypeGuildSettingsBorderwall:     _AuditTypeName[61:86],
	AuditTypeGuildSettingsFreeroles:      _AuditTypeName[86:110],
	AuditTypeGuildSettingsLeaver:         _AuditTypeName[110:131],
	AuditTypeGuildSettingsRules:          _AuditTypeName[131:151],
	AuditTypeGuildSettingsTempchannels:   _AuditTypeName[151:178],
	AuditTypeGuildSettingsTimeroles:      _AuditTypeName[178:202],
	AuditTypeGuildSettingsWelcomer:       _AuditTypeName[202:225],
	AuditTypeGuildSettingsWelcomerDms:    _AuditTypeName[225:252],
	AuditTypeGuildSettingsWelcomerImages: _AuditTypeName[252:282],
	AuditTypeGuildSettingsWelcomerText:   _AuditTypeName[282:310],
	AuditTypeGuilds:                      _AuditTypeName[310:316],
	AuditTypeUsers:                       _AuditTypeName[316:321],
	AuditTypeWelcomerImages:              _AuditTypeName[321:336],
	AuditTypeGuildFeatures:               _AuditTypeName[336:350],
}

// String implements the Stringer interface.
func (x AuditType) String() string {
	if str, ok := _AuditTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("AuditType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuditType) IsValid() bool {
	_, ok := _AuditTypeMap[x]
	return ok
}

var _AuditTypeValue = map[string]AuditType{
	_AuditTypeName[0:7]:     AuditTypeUnknown,
	_AuditTypeName[7:26]:    AuditTypeBorderwallRequests,
	_AuditTypeName[26:37]:   AuditTypeCustomBots,
	_AuditTypeName[37:61]:   AuditTypeGuildSettingsAutoroles,
	_AuditTypeName[61:86]:   AuditTypeGuildSettingsBorderwall,
	_AuditTypeName[86:110]:  AuditTypeGuildSettingsFreeroles,
	_AuditTypeName[110:131]: AuditTypeGuildSettingsLeaver,
	_AuditTypeName[131:151]: AuditTypeGuildSettingsRules,
	_AuditTypeName[151:178]: AuditTypeGuildSettingsTempchannels,
	_AuditTypeName[178:202]: AuditTypeGuildSettingsTimeroles,
	_AuditTypeName[202:225]: AuditTypeGuildSettingsWelcomer,
	_AuditTypeName[225:252]: AuditTypeGuildSettingsWelcomerDms,
	_AuditTypeName[252:282]: AuditTypeGuildSettingsWelcomerImages,
	_AuditTypeName[282:310]: AuditTypeGuildSettingsWelcomerText,
	_AuditTypeName[310:316]: AuditTypeGuilds,
	_AuditTypeName[316:321]: AuditTypeUsers,
	_AuditTypeName[321:336]: AuditTypeWelcomerImages,
	_AuditTypeName[336:350]: AuditTypeGuildFeatures,
}

// ParseAuditType attempts to convert a string to a AuditType.
func ParseAuditType(name string) (AuditType, error) {
	if x, ok := _AuditTypeValue[name]; ok {
		return x, nil
	}
	return AuditType(0), fmt.Errorf("%s is %w", name, ErrInvalidAuditType)
}

// MarshalText implements the text marshaller method.
func (x AuditType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *AuditType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseAuditType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *AuditType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
