// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_query.sql

package database

import (
	"context"
	"database/sql"
)

const InsertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (audit_uuid, created_at, guild_id, user_id, audit_type, changes_bytes)
    VALUES (uuid_generate_v7(), now(), $1, $2, $3, $4)
RETURNING
    audit_uuid, created_at, guild_id, user_id, audit_type, changes_bytes
`

type InsertAuditLogParams struct {
	GuildID      sql.NullInt64 `json:"guild_id"`
	UserID       int64         `json:"user_id"`
	AuditType    int32         `json:"audit_type"`
	ChangesBytes []byte        `json:"changes_bytes"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (*AuditLogs, error) {
	row := q.db.QueryRow(ctx, InsertAuditLog,
		arg.GuildID,
		arg.UserID,
		arg.AuditType,
		arg.ChangesBytes,
	)
	var i AuditLogs
	err := row.Scan(
		&i.AuditUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.UserID,
		&i.AuditType,
		&i.ChangesBytes,
	)
	return &i, err
}
