// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_query.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

const GetGuildAuditLogs = `-- name: GetGuildAuditLogs :many
SELECT
    created_at, user_id, audit_type, changes
FROM
    audit_logs
WHERE
    guild_id = $1
ORDER BY
    created_at ASC
`

type GetGuildAuditLogsRow struct {
	CreatedAt time.Time    `json:"created_at"`
	UserID    int64        `json:"user_id"`
	AuditType int32        `json:"audit_type"`
	Changes   pgtype.JSONB `json:"changes"`
}

func (q *Queries) GetGuildAuditLogs(ctx context.Context, guildID sql.NullInt64) ([]*GetGuildAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, GetGuildAuditLogs, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetGuildAuditLogsRow{}
	for rows.Next() {
		var i GetGuildAuditLogsRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.UserID,
			&i.AuditType,
			&i.Changes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (audit_uuid, created_at, guild_id, user_id, audit_type, changes)
    VALUES (uuid_generate_v7(), now(), $1, $2, $3, $4)
RETURNING
    audit_uuid, created_at, guild_id, user_id, audit_type, changes
`

type InsertAuditLogParams struct {
	GuildID   sql.NullInt64 `json:"guild_id"`
	UserID    int64         `json:"user_id"`
	AuditType int32         `json:"audit_type"`
	Changes   pgtype.JSONB  `json:"changes"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (*AuditLogs, error) {
	row := q.db.QueryRow(ctx, InsertAuditLog,
		arg.GuildID,
		arg.UserID,
		arg.AuditType,
		arg.Changes,
	)
	var i AuditLogs
	err := row.Scan(
		&i.AuditUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.UserID,
		&i.AuditType,
		&i.Changes,
	)
	return &i, err
}
