// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForCreateManyIngestMessageEvents implements pgx.CopyFromSource.
type iteratorForCreateManyIngestMessageEvents struct {
	rows                 []CreateManyIngestMessageEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateManyIngestMessageEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateManyIngestMessageEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MessageID,
		r.rows[0].GuildID,
		r.rows[0].ChannelID,
		r.rows[0].UserID,
		r.rows[0].EventType,
		r.rows[0].OccurredAt,
	}, nil
}

func (r iteratorForCreateManyIngestMessageEvents) Err() error {
	return nil
}

func (q *Queries) CreateManyIngestMessageEvents(ctx context.Context, arg []CreateManyIngestMessageEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ingest_message_events"}, []string{"message_id", "guild_id", "channel_id", "user_id", "event_type", "occurred_at"}, &iteratorForCreateManyIngestMessageEvents{rows: arg})
}

// iteratorForCreateManyInteractionCommands implements pgx.CopyFromSource.
type iteratorForCreateManyInteractionCommands struct {
	rows                 []CreateManyInteractionCommandsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateManyInteractionCommands) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateManyInteractionCommands) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ApplicationID,
		r.rows[0].Command,
		r.rows[0].InteractionID,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForCreateManyInteractionCommands) Err() error {
	return nil
}

func (q *Queries) CreateManyInteractionCommands(ctx context.Context, arg []CreateManyInteractionCommandsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"interaction_commands"}, []string{"application_id", "command", "interaction_id", "created_at"}, &iteratorForCreateManyInteractionCommands{rows: arg})
}

// iteratorForCreateManyScienceGuildEvents implements pgx.CopyFromSource.
type iteratorForCreateManyScienceGuildEvents struct {
	rows                 []CreateManyScienceGuildEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateManyScienceGuildEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateManyScienceGuildEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].GuildEventUuid,
		r.rows[0].GuildID,
		r.rows[0].UserID,
		r.rows[0].CreatedAt,
		r.rows[0].EventType,
		r.rows[0].Data,
	}, nil
}

func (r iteratorForCreateManyScienceGuildEvents) Err() error {
	return nil
}

func (q *Queries) CreateManyScienceGuildEvents(ctx context.Context, arg []CreateManyScienceGuildEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"science_guild_events"}, []string{"guild_event_uuid", "guild_id", "user_id", "created_at", "event_type", "data"}, &iteratorForCreateManyScienceGuildEvents{rows: arg})
}
