// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package database

import (
	"errors"
	"fmt"
)

const (
	// MembershipStatusUnknown is a MembershipStatus of type Unknown.
	MembershipStatusUnknown MembershipStatus = iota
	// MembershipStatusIdle is a MembershipStatus of type Idle.
	MembershipStatusIdle
	// MembershipStatusActive is a MembershipStatus of type Active.
	MembershipStatusActive
	// MembershipStatusExpired is a MembershipStatus of type Expired.
	MembershipStatusExpired
	// MembershipStatusRefunded is a MembershipStatus of type Refunded.
	MembershipStatusRefunded
	// MembershipStatusRemoved is a MembershipStatus of type Removed.
	MembershipStatusRemoved
)

var ErrInvalidMembershipStatus = errors.New("not a valid MembershipStatus")

const _MembershipStatusName = "unknownidleactiveexpiredrefundedremoved"

var _MembershipStatusMap = map[MembershipStatus]string{
	MembershipStatusUnknown:  _MembershipStatusName[0:7],
	MembershipStatusIdle:     _MembershipStatusName[7:11],
	MembershipStatusActive:   _MembershipStatusName[11:17],
	MembershipStatusExpired:  _MembershipStatusName[17:24],
	MembershipStatusRefunded: _MembershipStatusName[24:32],
	MembershipStatusRemoved:  _MembershipStatusName[32:39],
}

// String implements the Stringer interface.
func (x MembershipStatus) String() string {
	if str, ok := _MembershipStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("MembershipStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MembershipStatus) IsValid() bool {
	_, ok := _MembershipStatusMap[x]
	return ok
}

var _MembershipStatusValue = map[string]MembershipStatus{
	_MembershipStatusName[0:7]:   MembershipStatusUnknown,
	_MembershipStatusName[7:11]:  MembershipStatusIdle,
	_MembershipStatusName[11:17]: MembershipStatusActive,
	_MembershipStatusName[17:24]: MembershipStatusExpired,
	_MembershipStatusName[24:32]: MembershipStatusRefunded,
	_MembershipStatusName[32:39]: MembershipStatusRemoved,
}

// ParseMembershipStatus attempts to convert a string to a MembershipStatus.
func ParseMembershipStatus(name string) (MembershipStatus, error) {
	if x, ok := _MembershipStatusValue[name]; ok {
		return x, nil
	}
	return MembershipStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidMembershipStatus)
}

// MarshalText implements the text marshaller method.
func (x MembershipStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MembershipStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseMembershipStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// MembershipTypeUnknown is a MembershipType of type Unknown.
	MembershipTypeUnknown MembershipType = iota
	// MembershipTypeLegacyCustomBackgrounds is a MembershipType of type LegacyCustomBackgrounds.
	MembershipTypeLegacyCustomBackgrounds
	// MembershipTypeLegacyWelcomerPro is a MembershipType of type LegacyWelcomerPro.
	MembershipTypeLegacyWelcomerPro
	// MembershipTypeWelcomerPro is a MembershipType of type WelcomerPro.
	MembershipTypeWelcomerPro
	// MembershipTypeCustomBackgrounds is a MembershipType of type CustomBackgrounds.
	MembershipTypeCustomBackgrounds
)

var ErrInvalidMembershipType = errors.New("not a valid MembershipType")

const _MembershipTypeName = "unknownlegacyCustomBackgroundslegacyWelcomerProwelcomerProcustomBackgrounds"

var _MembershipTypeMap = map[MembershipType]string{
	MembershipTypeUnknown:                 _MembershipTypeName[0:7],
	MembershipTypeLegacyCustomBackgrounds: _MembershipTypeName[7:30],
	MembershipTypeLegacyWelcomerPro:       _MembershipTypeName[30:47],
	MembershipTypeWelcomerPro:             _MembershipTypeName[47:58],
	MembershipTypeCustomBackgrounds:       _MembershipTypeName[58:75],
}

// String implements the Stringer interface.
func (x MembershipType) String() string {
	if str, ok := _MembershipTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("MembershipType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MembershipType) IsValid() bool {
	_, ok := _MembershipTypeMap[x]
	return ok
}

var _MembershipTypeValue = map[string]MembershipType{
	_MembershipTypeName[0:7]:   MembershipTypeUnknown,
	_MembershipTypeName[7:30]:  MembershipTypeLegacyCustomBackgrounds,
	_MembershipTypeName[30:47]: MembershipTypeLegacyWelcomerPro,
	_MembershipTypeName[47:58]: MembershipTypeWelcomerPro,
	_MembershipTypeName[58:75]: MembershipTypeCustomBackgrounds,
}

// ParseMembershipType attempts to convert a string to a MembershipType.
func ParseMembershipType(name string) (MembershipType, error) {
	if x, ok := _MembershipTypeValue[name]; ok {
		return x, nil
	}
	return MembershipType(0), fmt.Errorf("%s is %w", name, ErrInvalidMembershipType)
}

// MarshalText implements the text marshaller method.
func (x MembershipType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MembershipType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseMembershipType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// PlatformTypeUnknown is a PlatformType of type Unknown.
	PlatformTypeUnknown PlatformType = iota
	// PlatformTypePaypal is a PlatformType of type Paypal.
	PlatformTypePaypal
	// PlatformTypePatreon is a PlatformType of type Patreon.
	PlatformTypePatreon
	// PlatformTypeStripe is a PlatformType of type Stripe.
	PlatformTypeStripe
	// PlatformTypePaypalSubscription is a PlatformType of type Paypal_subscription.
	PlatformTypePaypalSubscription
	// PlatformTypeDiscord is a PlatformType of type Discord.
	PlatformTypeDiscord
)

var ErrInvalidPlatformType = errors.New("not a valid PlatformType")

const _PlatformTypeName = "unknownpaypalpatreonstripepaypal_subscriptiondiscord"

var _PlatformTypeMap = map[PlatformType]string{
	PlatformTypeUnknown:            _PlatformTypeName[0:7],
	PlatformTypePaypal:             _PlatformTypeName[7:13],
	PlatformTypePatreon:            _PlatformTypeName[13:20],
	PlatformTypeStripe:             _PlatformTypeName[20:26],
	PlatformTypePaypalSubscription: _PlatformTypeName[26:45],
	PlatformTypeDiscord:            _PlatformTypeName[45:52],
}

// String implements the Stringer interface.
func (x PlatformType) String() string {
	if str, ok := _PlatformTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("PlatformType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PlatformType) IsValid() bool {
	_, ok := _PlatformTypeMap[x]
	return ok
}

var _PlatformTypeValue = map[string]PlatformType{
	_PlatformTypeName[0:7]:   PlatformTypeUnknown,
	_PlatformTypeName[7:13]:  PlatformTypePaypal,
	_PlatformTypeName[13:20]: PlatformTypePatreon,
	_PlatformTypeName[20:26]: PlatformTypeStripe,
	_PlatformTypeName[26:45]: PlatformTypePaypalSubscription,
	_PlatformTypeName[45:52]: PlatformTypeDiscord,
}

// ParsePlatformType attempts to convert a string to a PlatformType.
func ParsePlatformType(name string) (PlatformType, error) {
	if x, ok := _PlatformTypeValue[name]; ok {
		return x, nil
	}
	return PlatformType(0), fmt.Errorf("%s is %w", name, ErrInvalidPlatformType)
}

// MarshalText implements the text marshaller method.
func (x PlatformType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PlatformType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParsePlatformType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ScienceEventTypeUnknown is a ScienceEventType of type Unknown.
	ScienceEventTypeUnknown ScienceEventType = iota
)

var ErrInvalidScienceEventType = errors.New("not a valid ScienceEventType")

const _ScienceEventTypeName = "unknown"

var _ScienceEventTypeMap = map[ScienceEventType]string{
	ScienceEventTypeUnknown: _ScienceEventTypeName[0:7],
}

// String implements the Stringer interface.
func (x ScienceEventType) String() string {
	if str, ok := _ScienceEventTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ScienceEventType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ScienceEventType) IsValid() bool {
	_, ok := _ScienceEventTypeMap[x]
	return ok
}

var _ScienceEventTypeValue = map[string]ScienceEventType{
	_ScienceEventTypeName[0:7]: ScienceEventTypeUnknown,
}

// ParseScienceEventType attempts to convert a string to a ScienceEventType.
func ParseScienceEventType(name string) (ScienceEventType, error) {
	if x, ok := _ScienceEventTypeValue[name]; ok {
		return x, nil
	}
	return ScienceEventType(0), fmt.Errorf("%s is %w", name, ErrInvalidScienceEventType)
}

// MarshalText implements the text marshaller method.
func (x ScienceEventType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ScienceEventType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseScienceEventType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ScienceGuildEventTypeUnknown is a ScienceGuildEventType of type Unknown.
	ScienceGuildEventTypeUnknown ScienceGuildEventType = iota
	// ScienceGuildEventTypeUserJoin is a ScienceGuildEventType of type UserJoin.
	ScienceGuildEventTypeUserJoin
	// ScienceGuildEventTypeUserLeave is a ScienceGuildEventType of type UserLeave.
	ScienceGuildEventTypeUserLeave
	// ScienceGuildEventTypeUserWelcomed is a ScienceGuildEventType of type UserWelcomed.
	ScienceGuildEventTypeUserWelcomed
	// ScienceGuildEventTypeTimeRoleGiven is a ScienceGuildEventType of type TimeRoleGiven.
	ScienceGuildEventTypeTimeRoleGiven
	// ScienceGuildEventTypeBorderwallChallenge is a ScienceGuildEventType of type BorderwallChallenge.
	ScienceGuildEventTypeBorderwallChallenge
	// ScienceGuildEventTypeBorderwallCompleted is a ScienceGuildEventType of type BorderwallCompleted.
	ScienceGuildEventTypeBorderwallCompleted
	// ScienceGuildEventTypeTempChannelCreated is a ScienceGuildEventType of type TempChannelCreated.
	ScienceGuildEventTypeTempChannelCreated
	// ScienceGuildEventTypeMembershipReceived is a ScienceGuildEventType of type MembershipReceived.
	ScienceGuildEventTypeMembershipReceived
	// ScienceGuildEventTypeMembershipRemoved is a ScienceGuildEventType of type MembershipRemoved.
	ScienceGuildEventTypeMembershipRemoved
	// ScienceGuildEventTypeGuildJoin is a ScienceGuildEventType of type GuildJoin.
	ScienceGuildEventTypeGuildJoin
	// ScienceGuildEventTypeGuildLeave is a ScienceGuildEventType of type GuildLeave.
	ScienceGuildEventTypeGuildLeave
	// ScienceGuildEventTypeGuildOnboarded is a ScienceGuildEventType of type GuildOnboarded.
	ScienceGuildEventTypeGuildOnboarded
	// ScienceGuildEventTypeGuildUserOnboarded is a ScienceGuildEventType of type GuildUserOnboarded.
	ScienceGuildEventTypeGuildUserOnboarded
)

var ErrInvalidScienceGuildEventType = errors.New("not a valid ScienceGuildEventType")

const _ScienceGuildEventTypeName = "unknownuserJoinuserLeaveuserWelcomedtimeRoleGivenborderwallChallengeborderwallCompletedtempChannelCreatedmembershipReceivedmembershipRemovedguildJoinguildLeaveguildOnboardedguildUserOnboarded"

var _ScienceGuildEventTypeMap = map[ScienceGuildEventType]string{
	ScienceGuildEventTypeUnknown:             _ScienceGuildEventTypeName[0:7],
	ScienceGuildEventTypeUserJoin:            _ScienceGuildEventTypeName[7:15],
	ScienceGuildEventTypeUserLeave:           _ScienceGuildEventTypeName[15:24],
	ScienceGuildEventTypeUserWelcomed:        _ScienceGuildEventTypeName[24:36],
	ScienceGuildEventTypeTimeRoleGiven:       _ScienceGuildEventTypeName[36:49],
	ScienceGuildEventTypeBorderwallChallenge: _ScienceGuildEventTypeName[49:68],
	ScienceGuildEventTypeBorderwallCompleted: _ScienceGuildEventTypeName[68:87],
	ScienceGuildEventTypeTempChannelCreated:  _ScienceGuildEventTypeName[87:105],
	ScienceGuildEventTypeMembershipReceived:  _ScienceGuildEventTypeName[105:123],
	ScienceGuildEventTypeMembershipRemoved:   _ScienceGuildEventTypeName[123:140],
	ScienceGuildEventTypeGuildJoin:           _ScienceGuildEventTypeName[140:149],
	ScienceGuildEventTypeGuildLeave:          _ScienceGuildEventTypeName[149:159],
	ScienceGuildEventTypeGuildOnboarded:      _ScienceGuildEventTypeName[159:173],
	ScienceGuildEventTypeGuildUserOnboarded:  _ScienceGuildEventTypeName[173:191],
}

// String implements the Stringer interface.
func (x ScienceGuildEventType) String() string {
	if str, ok := _ScienceGuildEventTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ScienceGuildEventType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ScienceGuildEventType) IsValid() bool {
	_, ok := _ScienceGuildEventTypeMap[x]
	return ok
}

var _ScienceGuildEventTypeValue = map[string]ScienceGuildEventType{
	_ScienceGuildEventTypeName[0:7]:     ScienceGuildEventTypeUnknown,
	_ScienceGuildEventTypeName[7:15]:    ScienceGuildEventTypeUserJoin,
	_ScienceGuildEventTypeName[15:24]:   ScienceGuildEventTypeUserLeave,
	_ScienceGuildEventTypeName[24:36]:   ScienceGuildEventTypeUserWelcomed,
	_ScienceGuildEventTypeName[36:49]:   ScienceGuildEventTypeTimeRoleGiven,
	_ScienceGuildEventTypeName[49:68]:   ScienceGuildEventTypeBorderwallChallenge,
	_ScienceGuildEventTypeName[68:87]:   ScienceGuildEventTypeBorderwallCompleted,
	_ScienceGuildEventTypeName[87:105]:  ScienceGuildEventTypeTempChannelCreated,
	_ScienceGuildEventTypeName[105:123]: ScienceGuildEventTypeMembershipReceived,
	_ScienceGuildEventTypeName[123:140]: ScienceGuildEventTypeMembershipRemoved,
	_ScienceGuildEventTypeName[140:149]: ScienceGuildEventTypeGuildJoin,
	_ScienceGuildEventTypeName[149:159]: ScienceGuildEventTypeGuildLeave,
	_ScienceGuildEventTypeName[159:173]: ScienceGuildEventTypeGuildOnboarded,
	_ScienceGuildEventTypeName[173:191]: ScienceGuildEventTypeGuildUserOnboarded,
}

// ParseScienceGuildEventType attempts to convert a string to a ScienceGuildEventType.
func ParseScienceGuildEventType(name string) (ScienceGuildEventType, error) {
	if x, ok := _ScienceGuildEventTypeValue[name]; ok {
		return x, nil
	}
	return ScienceGuildEventType(0), fmt.Errorf("%s is %w", name, ErrInvalidScienceGuildEventType)
}

// MarshalText implements the text marshaller method.
func (x ScienceGuildEventType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ScienceGuildEventType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseScienceGuildEventType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// TransactionStatusUnknown is a TransactionStatus of type Unknown.
	TransactionStatusUnknown TransactionStatus = iota
	// TransactionStatusPending is a TransactionStatus of type Pending.
	TransactionStatusPending
	// TransactionStatusCompleted is a TransactionStatus of type Completed.
	TransactionStatusCompleted
	// TransactionStatusRefunded is a TransactionStatus of type Refunded.
	TransactionStatusRefunded
)

var ErrInvalidTransactionStatus = errors.New("not a valid TransactionStatus")

const _TransactionStatusName = "unknownpendingcompletedrefunded"

var _TransactionStatusMap = map[TransactionStatus]string{
	TransactionStatusUnknown:   _TransactionStatusName[0:7],
	TransactionStatusPending:   _TransactionStatusName[7:14],
	TransactionStatusCompleted: _TransactionStatusName[14:23],
	TransactionStatusRefunded:  _TransactionStatusName[23:31],
}

// String implements the Stringer interface.
func (x TransactionStatus) String() string {
	if str, ok := _TransactionStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("TransactionStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TransactionStatus) IsValid() bool {
	_, ok := _TransactionStatusMap[x]
	return ok
}

var _TransactionStatusValue = map[string]TransactionStatus{
	_TransactionStatusName[0:7]:   TransactionStatusUnknown,
	_TransactionStatusName[7:14]:  TransactionStatusPending,
	_TransactionStatusName[14:23]: TransactionStatusCompleted,
	_TransactionStatusName[23:31]: TransactionStatusRefunded,
}

// ParseTransactionStatus attempts to convert a string to a TransactionStatus.
func ParseTransactionStatus(name string) (TransactionStatus, error) {
	if x, ok := _TransactionStatusValue[name]; ok {
		return x, nil
	}
	return TransactionStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidTransactionStatus)
}

// MarshalText implements the text marshaller method.
func (x TransactionStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TransactionStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseTransactionStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
