// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: easter_eggs_query.sql

package database

import (
	"context"

	"github.com/WelcomerTeam/Discord/discord"
	"github.com/gofrs/uuid"
)

const GetCollectedEasterEggsByGuildID = `-- name: GetCollectedEasterEggsByGuildID :many
SELECT COUNT(*)::int, user_id
FROM easter_eggs
WHERE guild_id = $1
GROUP BY user_id
ORDER BY COUNT(*) DESC
LIMIT 20
`

type GetCollectedEasterEggsByGuildIDRow struct {
	Column1 int32 `json:"column_1"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GetCollectedEasterEggsByGuildID(ctx context.Context, guildID int64) ([]*GetCollectedEasterEggsByGuildIDRow, error) {
	rows, err := q.db.Query(ctx, GetCollectedEasterEggsByGuildID, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCollectedEasterEggsByGuildIDRow{}
	for rows.Next() {
		var i GetCollectedEasterEggsByGuildIDRow
		if err := rows.Scan(&i.Column1, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEasterEggsByUserID = `-- name: GetEasterEggsByUserID :many
SELECT claimed_egg, MIN(created_at), MAX(created_at), COUNT(*)
FROM easter_eggs
WHERE user_id = $1
GROUP BY claimed_egg
ORDER BY COUNT(*) DESC
`

type GetEasterEggsByUserIDRow struct {
	ClaimedEgg string            `json:"claimed_egg"`
	Min        interface{}       `json:"min"`
	Max        interface{}       `json:"max"`
	Count      discord.Snowflake `json:"count"`
}

func (q *Queries) GetEasterEggsByUserID(ctx context.Context, userID int64) ([]*GetEasterEggsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, GetEasterEggsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEasterEggsByUserIDRow{}
	for rows.Next() {
		var i GetEasterEggsByUserIDRow
		if err := rows.Scan(
			&i.ClaimedEgg,
			&i.Min,
			&i.Max,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertEasterEgg = `-- name: InsertEasterEgg :one
INSERT INTO easter_eggs(easter_egg_uuid, guild_id, channel_id, message_id, user_id, claimed_egg, created_at, wm_user_id)
VALUES (uuid_generate_v7(), $1, $2, $3, $4, $5, NOW(), $6)
ON CONFLICT (guild_id, channel_id, message_id) DO NOTHING
RETURNING easter_egg_uuid
`

type InsertEasterEggParams struct {
	GuildID    int64  `json:"guild_id"`
	ChannelID  int64  `json:"channel_id"`
	MessageID  int64  `json:"message_id"`
	UserID     int64  `json:"user_id"`
	ClaimedEgg string `json:"claimed_egg"`
	WmUserID   string `json:"wm_user_id"`
}

func (q *Queries) InsertEasterEgg(ctx context.Context, arg InsertEasterEggParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, InsertEasterEgg,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.UserID,
		arg.ClaimedEgg,
		arg.WmUserID,
	)
	var easter_egg_uuid uuid.UUID
	err := row.Scan(&easter_egg_uuid)
	return easter_egg_uuid, err
}
