// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: guild_settings_welcomer_query.sql

package database

import (
	"context"
)

const CreateOrUpdateWelcomerGuildSettings = `-- name: CreateOrUpdateWelcomerGuildSettings :one
INSERT INTO guild_settings_welcomer (guild_id, auto_delete_welcome_messages, welcome_message_lifetime, auto_delete_welcome_messages_on_leave)
    VALUES ($1, $2, $3, $4)
ON CONFLICT(guild_id) DO UPDATE
    SET auto_delete_welcome_messages = EXCLUDED.auto_delete_welcome_messages,
        welcome_message_lifetime = EXCLUDED.welcome_message_lifetime,
        auto_delete_welcome_messages_on_leave = EXCLUDED.auto_delete_welcome_messages_on_leave
RETURNING
    guild_id, auto_delete_welcome_messages, welcome_message_lifetime, auto_delete_welcome_messages_on_leave
`

type CreateOrUpdateWelcomerGuildSettingsParams struct {
	GuildID                          int64 `json:"guild_id"`
	AutoDeleteWelcomeMessages        bool  `json:"auto_delete_welcome_messages"`
	WelcomeMessageLifetime           int32 `json:"welcome_message_lifetime"`
	AutoDeleteWelcomeMessagesOnLeave bool  `json:"auto_delete_welcome_messages_on_leave"`
}

func (q *Queries) CreateOrUpdateWelcomerGuildSettings(ctx context.Context, arg CreateOrUpdateWelcomerGuildSettingsParams) (*GuildSettingsWelcomer, error) {
	row := q.db.QueryRow(ctx, CreateOrUpdateWelcomerGuildSettings,
		arg.GuildID,
		arg.AutoDeleteWelcomeMessages,
		arg.WelcomeMessageLifetime,
		arg.AutoDeleteWelcomeMessagesOnLeave,
	)
	var i GuildSettingsWelcomer
	err := row.Scan(
		&i.GuildID,
		&i.AutoDeleteWelcomeMessages,
		&i.WelcomeMessageLifetime,
		&i.AutoDeleteWelcomeMessagesOnLeave,
	)
	return &i, err
}

const CreateWelcomerGuildSettings = `-- name: CreateWelcomerGuildSettings :one
INSERT INTO guild_settings_welcomer (guild_id, auto_delete_welcome_messages, welcome_message_lifetime, auto_delete_welcome_messages_on_leave)
    VALUES ($1, $2, $3, $4)
RETURNING
    guild_id, auto_delete_welcome_messages, welcome_message_lifetime, auto_delete_welcome_messages_on_leave
`

type CreateWelcomerGuildSettingsParams struct {
	GuildID                          int64 `json:"guild_id"`
	AutoDeleteWelcomeMessages        bool  `json:"auto_delete_welcome_messages"`
	WelcomeMessageLifetime           int32 `json:"welcome_message_lifetime"`
	AutoDeleteWelcomeMessagesOnLeave bool  `json:"auto_delete_welcome_messages_on_leave"`
}

func (q *Queries) CreateWelcomerGuildSettings(ctx context.Context, arg CreateWelcomerGuildSettingsParams) (*GuildSettingsWelcomer, error) {
	row := q.db.QueryRow(ctx, CreateWelcomerGuildSettings,
		arg.GuildID,
		arg.AutoDeleteWelcomeMessages,
		arg.WelcomeMessageLifetime,
		arg.AutoDeleteWelcomeMessagesOnLeave,
	)
	var i GuildSettingsWelcomer
	err := row.Scan(
		&i.GuildID,
		&i.AutoDeleteWelcomeMessages,
		&i.WelcomeMessageLifetime,
		&i.AutoDeleteWelcomeMessagesOnLeave,
	)
	return &i, err
}

const GetWelcomerGuildSettings = `-- name: GetWelcomerGuildSettings :one
SELECT
    guild_id, auto_delete_welcome_messages, welcome_message_lifetime, auto_delete_welcome_messages_on_leave
FROM
    guild_settings_welcomer
WHERE
    guild_id = $1
`

func (q *Queries) GetWelcomerGuildSettings(ctx context.Context, guildID int64) (*GuildSettingsWelcomer, error) {
	row := q.db.QueryRow(ctx, GetWelcomerGuildSettings, guildID)
	var i GuildSettingsWelcomer
	err := row.Scan(
		&i.GuildID,
		&i.AutoDeleteWelcomeMessages,
		&i.WelcomeMessageLifetime,
		&i.AutoDeleteWelcomeMessagesOnLeave,
	)
	return &i, err
}

const UpdateWelcomerGuildSettings = `-- name: UpdateWelcomerGuildSettings :execrows
UPDATE
    guild_settings_welcomer
SET
    auto_delete_welcome_messages = $2,
    welcome_message_lifetime = $3,
    auto_delete_welcome_messages_on_leave = $4
WHERE
    guild_id = $1
`

type UpdateWelcomerGuildSettingsParams struct {
	GuildID                          int64 `json:"guild_id"`
	AutoDeleteWelcomeMessages        bool  `json:"auto_delete_welcome_messages"`
	WelcomeMessageLifetime           int32 `json:"welcome_message_lifetime"`
	AutoDeleteWelcomeMessagesOnLeave bool  `json:"auto_delete_welcome_messages_on_leave"`
}

func (q *Queries) UpdateWelcomerGuildSettings(ctx context.Context, arg UpdateWelcomerGuildSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, UpdateWelcomerGuildSettings,
		arg.GuildID,
		arg.AutoDeleteWelcomeMessages,
		arg.WelcomeMessageLifetime,
		arg.AutoDeleteWelcomeMessagesOnLeave,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
