// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_settings_reaction_roles_query.sql

package database

import (
	"context"

	"github.com/jackc/pgtype"
)

const CreateOrUpdateReactionRolesGuildSettings = `-- name: CreateOrUpdateReactionRolesGuildSettings :one
INSERT INTO guild_settings_reaction_roles (guild_id, toggle_enabled, reaction_roles)
    VALUES ($1, $2, $3)
ON CONFLICT(guild_id) DO UPDATE
    SET toggle_enabled = EXCLUDED.toggle_enabled,
        reaction_roles = EXCLUDED.reaction_roles
RETURNING
    guild_id, toggle_enabled, reaction_roles
`

type CreateOrUpdateReactionRolesGuildSettingsParams struct {
	GuildID       int64        `json:"guild_id"`
	ToggleEnabled bool         `json:"toggle_enabled"`
	ReactionRoles pgtype.JSONB `json:"reaction_roles"`
}

func (q *Queries) CreateOrUpdateReactionRolesGuildSettings(ctx context.Context, arg CreateOrUpdateReactionRolesGuildSettingsParams) (*GuildSettingsReactionRoles, error) {
	row := q.db.QueryRow(ctx, CreateOrUpdateReactionRolesGuildSettings, arg.GuildID, arg.ToggleEnabled, arg.ReactionRoles)
	var i GuildSettingsReactionRoles
	err := row.Scan(&i.GuildID, &i.ToggleEnabled, &i.ReactionRoles)
	return &i, err
}

const CreateReactionRolesGuildSettings = `-- name: CreateReactionRolesGuildSettings :one
INSERT INTO guild_settings_reaction_roles (guild_id, toggle_enabled, reaction_roles)
    VALUES ($1, $2, $3)
RETURNING
    guild_id, toggle_enabled, reaction_roles
`

type CreateReactionRolesGuildSettingsParams struct {
	GuildID       int64        `json:"guild_id"`
	ToggleEnabled bool         `json:"toggle_enabled"`
	ReactionRoles pgtype.JSONB `json:"reaction_roles"`
}

func (q *Queries) CreateReactionRolesGuildSettings(ctx context.Context, arg CreateReactionRolesGuildSettingsParams) (*GuildSettingsReactionRoles, error) {
	row := q.db.QueryRow(ctx, CreateReactionRolesGuildSettings, arg.GuildID, arg.ToggleEnabled, arg.ReactionRoles)
	var i GuildSettingsReactionRoles
	err := row.Scan(&i.GuildID, &i.ToggleEnabled, &i.ReactionRoles)
	return &i, err
}

const GetReactionRolesGuildSettings = `-- name: GetReactionRolesGuildSettings :one
SELECT
    guild_id, toggle_enabled, reaction_roles
FROM
    guild_settings_reaction_roles
WHERE
    guild_id = $1
`

func (q *Queries) GetReactionRolesGuildSettings(ctx context.Context, guildID int64) (*GuildSettingsReactionRoles, error) {
	row := q.db.QueryRow(ctx, GetReactionRolesGuildSettings, guildID)
	var i GuildSettingsReactionRoles
	err := row.Scan(&i.GuildID, &i.ToggleEnabled, &i.ReactionRoles)
	return &i, err
}

const UpdateReactionRolesGuildSettings = `-- name: UpdateReactionRolesGuildSettings :execrows
UPDATE
    guild_settings_reaction_roles
SET
    toggle_enabled = $2,
    reaction_roles = $3
WHERE
    guild_id = $1
`

type UpdateReactionRolesGuildSettingsParams struct {
	GuildID       int64        `json:"guild_id"`
	ToggleEnabled bool         `json:"toggle_enabled"`
	ReactionRoles pgtype.JSONB `json:"reaction_roles"`
}

func (q *Queries) UpdateReactionRolesGuildSettings(ctx context.Context, arg UpdateReactionRolesGuildSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, UpdateReactionRolesGuildSettings, arg.GuildID, arg.ToggleEnabled, arg.ReactionRoles)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
