// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_giveaways_entries_query.sql

package database

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
)

const AddGiveawayEntry = `-- name: AddGiveawayEntry :one
INSERT INTO guild_giveaways_entries (guild_giveaway_entry_uuid, giveaway_uuid, user_id, created_at)
VALUES (uuid_generate_v7(), $1, $2, NOW())
ON CONFLICT (giveaway_uuid, user_id) DO NOTHING
RETURNING guild_giveaway_entry_uuid
`

type AddGiveawayEntryParams struct {
	GiveawayUuid uuid.UUID `json:"giveaway_uuid"`
	UserID       int64     `json:"user_id"`
}

func (q *Queries) AddGiveawayEntry(ctx context.Context, arg AddGiveawayEntryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, AddGiveawayEntry, arg.GiveawayUuid, arg.UserID)
	var guild_giveaway_entry_uuid uuid.UUID
	err := row.Scan(&guild_giveaway_entry_uuid)
	return guild_giveaway_entry_uuid, err
}

const CountGiveawayEntries = `-- name: CountGiveawayEntries :one
SELECT COUNT(*)::int FROM guild_giveaways_entries
WHERE giveaway_uuid = $1
`

func (q *Queries) CountGiveawayEntries(ctx context.Context, giveawayUuid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, CountGiveawayEntries, giveawayUuid)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const GetGiveawayEntries = `-- name: GetGiveawayEntries :many
SELECT guild_giveaway_entry_uuid, giveaway_uuid, user_id, created_at FROM guild_giveaways_entries
WHERE giveaway_uuid = $1
ORDER BY created_at DESC
`

func (q *Queries) GetGiveawayEntries(ctx context.Context, giveawayUuid uuid.UUID) ([]*GuildGiveawaysEntries, error) {
	rows, err := q.db.Query(ctx, GetGiveawayEntries, giveawayUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GuildGiveawaysEntries{}
	for rows.Next() {
		var i GuildGiveawaysEntries
		if err := rows.Scan(
			&i.GuildGiveawayEntryUuid,
			&i.GiveawayUuid,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetGiveawayEntryFromMessageID = `-- name: GetGiveawayEntryFromMessageID :one
SELECT
    guild_giveaway_entry_uuid, guild_giveaways_entries.giveaway_uuid, user_id, guild_giveaways_entries.created_at, guild_giveaways.giveaway_uuid, guild_giveaways.created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, giveaway_prizes, allow_entries, announce_winners, show_prizes, show_entries, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id
FROM
    guild_giveaways_entries
    JOIN guild_giveaways ON guild_giveaways.giveaway_uuid = guild_giveaways_entries.giveaway_uuid
WHERE
    guild_giveaways.guild_id = $1
    AND guild_giveaways.channel_id = $2
    AND guild_giveaways.message_id = $3
`

type GetGiveawayEntryFromMessageIDParams struct {
	GuildID   int64 `json:"guild_id"`
	ChannelID int64 `json:"channel_id"`
	MessageID int64 `json:"message_id"`
}

type GetGiveawayEntryFromMessageIDRow struct {
	GuildGiveawayEntryUuid uuid.UUID    `json:"guild_giveaway_entry_uuid"`
	GiveawayUuid           uuid.UUID    `json:"giveaway_uuid"`
	UserID                 int64        `json:"user_id"`
	CreatedAt              time.Time    `json:"created_at"`
	GiveawayUuid_2         uuid.UUID    `json:"giveaway_uuid_2"`
	CreatedAt_2            time.Time    `json:"created_at_2"`
	GuildID                int64        `json:"guild_id"`
	CreatedBy              int64        `json:"created_by"`
	HasEnded               bool         `json:"has_ended"`
	IsSetup                bool         `json:"is_setup"`
	Title                  string       `json:"title"`
	Description            string       `json:"description"`
	AccentColour           int64        `json:"accent_colour"`
	ImageUrl               string       `json:"image_url"`
	StartTime              time.Time    `json:"start_time"`
	EndTime                time.Time    `json:"end_time"`
	GiveawayPrizes         pgtype.JSONB `json:"giveaway_prizes"`
	AllowEntries           bool         `json:"allow_entries"`
	AnnounceWinners        bool         `json:"announce_winners"`
	ShowPrizes             bool         `json:"show_prizes"`
	ShowEntries            bool         `json:"show_entries"`
	RolesAllowed           pgtype.JSONB `json:"roles_allowed"`
	RolesExcluded          pgtype.JSONB `json:"roles_excluded"`
	MinimumJoinDate        time.Time    `json:"minimum_join_date"`
	MessageID              int64        `json:"message_id"`
	ChannelID              int64        `json:"channel_id"`
}

func (q *Queries) GetGiveawayEntryFromMessageID(ctx context.Context, arg GetGiveawayEntryFromMessageIDParams) (*GetGiveawayEntryFromMessageIDRow, error) {
	row := q.db.QueryRow(ctx, GetGiveawayEntryFromMessageID, arg.GuildID, arg.ChannelID, arg.MessageID)
	var i GetGiveawayEntryFromMessageIDRow
	err := row.Scan(
		&i.GuildGiveawayEntryUuid,
		&i.GiveawayUuid,
		&i.UserID,
		&i.CreatedAt,
		&i.GiveawayUuid_2,
		&i.CreatedAt_2,
		&i.GuildID,
		&i.CreatedBy,
		&i.HasEnded,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.GiveawayPrizes,
		&i.AllowEntries,
		&i.AnnounceWinners,
		&i.ShowPrizes,
		&i.ShowEntries,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
	)
	return &i, err
}

const GetGiveawayEntryUsers = `-- name: GetGiveawayEntryUsers :many
SELECT user_id FROM guild_giveaways_entries
WHERE giveaway_uuid = $1
`

func (q *Queries) GetGiveawayEntryUsers(ctx context.Context, giveawayUuid uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, GetGiveawayEntryUsers, giveawayUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveGiveawayEntry = `-- name: RemoveGiveawayEntry :exec
DELETE FROM guild_giveaways_entries
WHERE giveaway_uuid = $1 AND user_id = $2
`

type RemoveGiveawayEntryParams struct {
	GiveawayUuid uuid.UUID `json:"giveaway_uuid"`
	UserID       int64     `json:"user_id"`
}

func (q *Queries) RemoveGiveawayEntry(ctx context.Context, arg RemoveGiveawayEntryParams) error {
	_, err := q.db.Exec(ctx, RemoveGiveawayEntry, arg.GiveawayUuid, arg.UserID)
	return err
}
