// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: guild_settings_welcomer_text_query.sql

package database

import (
	"context"

	"github.com/jackc/pgtype"
)

const CreateOrUpdateWelcomerTextGuildSettings = `-- name: CreateOrUpdateWelcomerTextGuildSettings :one
INSERT INTO guild_settings_welcomer_text (guild_id, toggle_enabled, channel, message_format)
    VALUES ($1, $2, $3, $4)
ON CONFLICT(guild_id) DO UPDATE
    SET toggle_enabled = EXCLUDED.toggle_enabled,
        channel = EXCLUDED.channel,
        message_format = EXCLUDED.message_format
RETURNING
    guild_id, toggle_enabled, channel, message_format
`

type CreateOrUpdateWelcomerTextGuildSettingsParams struct {
	GuildID       int64        `json:"guild_id"`
	ToggleEnabled bool         `json:"toggle_enabled"`
	Channel       int64        `json:"channel"`
	MessageFormat pgtype.JSONB `json:"message_format"`
}

func (q *Queries) CreateOrUpdateWelcomerTextGuildSettings(ctx context.Context, arg *CreateOrUpdateWelcomerTextGuildSettingsParams) (*GuildSettingsWelcomerText, error) {
	row := q.db.QueryRow(ctx, CreateOrUpdateWelcomerTextGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.Channel,
		arg.MessageFormat,
	)
	var i GuildSettingsWelcomerText
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.Channel,
		&i.MessageFormat,
	)
	return &i, err
}

const CreateWelcomerTextGuildSettings = `-- name: CreateWelcomerTextGuildSettings :one
INSERT INTO guild_settings_welcomer_text (guild_id, toggle_enabled, channel, message_format)
    VALUES ($1, $2, $3, $4)
RETURNING
    guild_id, toggle_enabled, channel, message_format
`

type CreateWelcomerTextGuildSettingsParams struct {
	GuildID       int64        `json:"guild_id"`
	ToggleEnabled bool         `json:"toggle_enabled"`
	Channel       int64        `json:"channel"`
	MessageFormat pgtype.JSONB `json:"message_format"`
}

func (q *Queries) CreateWelcomerTextGuildSettings(ctx context.Context, arg *CreateWelcomerTextGuildSettingsParams) (*GuildSettingsWelcomerText, error) {
	row := q.db.QueryRow(ctx, CreateWelcomerTextGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.Channel,
		arg.MessageFormat,
	)
	var i GuildSettingsWelcomerText
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.Channel,
		&i.MessageFormat,
	)
	return &i, err
}

const GetWelcomerTextGuildSettings = `-- name: GetWelcomerTextGuildSettings :one
SELECT
    guild_id, toggle_enabled, channel, message_format
FROM
    guild_settings_welcomer_text
WHERE
    guild_id = $1
`

func (q *Queries) GetWelcomerTextGuildSettings(ctx context.Context, guildID int64) (*GuildSettingsWelcomerText, error) {
	row := q.db.QueryRow(ctx, GetWelcomerTextGuildSettings, guildID)
	var i GuildSettingsWelcomerText
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.Channel,
		&i.MessageFormat,
	)
	return &i, err
}

const UpdateWelcomerTextGuildSettings = `-- name: UpdateWelcomerTextGuildSettings :execrows
UPDATE
    guild_settings_welcomer_text
SET
    toggle_enabled = $2,
    channel = $3,
    message_format = $4
WHERE
    guild_id = $1
`

type UpdateWelcomerTextGuildSettingsParams struct {
	GuildID       int64        `json:"guild_id"`
	ToggleEnabled bool         `json:"toggle_enabled"`
	Channel       int64        `json:"channel"`
	MessageFormat pgtype.JSONB `json:"message_format"`
}

func (q *Queries) UpdateWelcomerTextGuildSettings(ctx context.Context, arg *UpdateWelcomerTextGuildSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, UpdateWelcomerTextGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.Channel,
		arg.MessageFormat,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
