// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_polls_entries_query.sql

package database

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
)

const AddPollEntry = `-- name: AddPollEntry :one
INSERT INTO guild_polls_entries (guild_poll_entry_uuid, poll_uuid, user_id, created_at, option_index)
VALUES (uuid_generate_v7(), $1, $2, NOW(), $3)
ON CONFLICT (poll_uuid, user_id) DO UPDATE SET option_index = EXCLUDED.option_index, created_at = NOW()
RETURNING guild_poll_entry_uuid
`

type AddPollEntryParams struct {
	PollUuid    uuid.UUID `json:"poll_uuid"`
	UserID      int64     `json:"user_id"`
	OptionIndex int32     `json:"option_index"`
}

func (q *Queries) AddPollEntry(ctx context.Context, arg AddPollEntryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, AddPollEntry, arg.PollUuid, arg.UserID, arg.OptionIndex)
	var guild_poll_entry_uuid uuid.UUID
	err := row.Scan(&guild_poll_entry_uuid)
	return guild_poll_entry_uuid, err
}

const CountPollEntriesByUniqueUsers = `-- name: CountPollEntriesByUniqueUsers :one
SELECT COUNT(user_id)::int FROM guild_polls_entries
WHERE poll_uuid = $1
`

func (q *Queries) CountPollEntriesByUniqueUsers(ctx context.Context, pollUuid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, CountPollEntriesByUniqueUsers, pollUuid)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const GetPollEntries = `-- name: GetPollEntries :many
SELECT guild_poll_entry_uuid, poll_uuid, user_id, option_index, created_at FROM guild_polls_entries
WHERE poll_uuid = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPollEntries(ctx context.Context, pollUuid uuid.UUID) ([]*GuildPollsEntries, error) {
	rows, err := q.db.Query(ctx, GetPollEntries, pollUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GuildPollsEntries{}
	for rows.Next() {
		var i GuildPollsEntries
		if err := rows.Scan(
			&i.GuildPollEntryUuid,
			&i.PollUuid,
			&i.UserID,
			&i.OptionIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPollEntriesForUser = `-- name: GetPollEntriesForUser :many
SELECT guild_poll_entry_uuid, poll_uuid, user_id, option_index, created_at FROM guild_polls_entries
WHERE poll_uuid = $1 AND user_id = $2
ORDER BY created_at DESC
`

type GetPollEntriesForUserParams struct {
	PollUuid uuid.UUID `json:"poll_uuid"`
	UserID   int64     `json:"user_id"`
}

func (q *Queries) GetPollEntriesForUser(ctx context.Context, arg GetPollEntriesForUserParams) ([]*GuildPollsEntries, error) {
	rows, err := q.db.Query(ctx, GetPollEntriesForUser, arg.PollUuid, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GuildPollsEntries{}
	for rows.Next() {
		var i GuildPollsEntries
		if err := rows.Scan(
			&i.GuildPollEntryUuid,
			&i.PollUuid,
			&i.UserID,
			&i.OptionIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPollEntriesFromMessageID = `-- name: GetPollEntriesFromMessageID :many
SELECT
    guild_poll_entry_uuid, guild_polls_entries.poll_uuid, user_id, option_index, guild_polls_entries.created_at, guild_polls.poll_uuid, guild_polls.created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, poll_options, is_anonymous, maximum_selections, resubmissions, results_visibility, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id
FROM
    guild_polls_entries
    JOIN guild_polls ON guild_polls.poll_uuid = guild_polls_entries.poll_uuid
WHERE
    guild_polls.guild_id = $1
    AND guild_polls.channel_id = $2
    AND guild_polls.message_id = $3
`

type GetPollEntriesFromMessageIDParams struct {
	GuildID   int64 `json:"guild_id"`
	ChannelID int64 `json:"channel_id"`
	MessageID int64 `json:"message_id"`
}

type GetPollEntriesFromMessageIDRow struct {
	GuildPollEntryUuid uuid.UUID    `json:"guild_poll_entry_uuid"`
	PollUuid           uuid.UUID    `json:"poll_uuid"`
	UserID             int64        `json:"user_id"`
	OptionIndex        int32        `json:"option_index"`
	CreatedAt          time.Time    `json:"created_at"`
	PollUuid_2         uuid.UUID    `json:"poll_uuid_2"`
	CreatedAt_2        time.Time    `json:"created_at_2"`
	GuildID            int64        `json:"guild_id"`
	CreatedBy          int64        `json:"created_by"`
	HasEnded           bool         `json:"has_ended"`
	IsSetup            bool         `json:"is_setup"`
	Title              string       `json:"title"`
	Description        string       `json:"description"`
	AccentColour       int64        `json:"accent_colour"`
	ImageUrl           string       `json:"image_url"`
	StartTime          time.Time    `json:"start_time"`
	EndTime            time.Time    `json:"end_time"`
	PollOptions        pgtype.JSONB `json:"poll_options"`
	IsAnonymous        bool         `json:"is_anonymous"`
	MaximumSelections  int32        `json:"maximum_selections"`
	Resubmissions      string       `json:"resubmissions"`
	ResultsVisibility  string       `json:"results_visibility"`
	RolesAllowed       pgtype.JSONB `json:"roles_allowed"`
	RolesExcluded      pgtype.JSONB `json:"roles_excluded"`
	MinimumJoinDate    time.Time    `json:"minimum_join_date"`
	MessageID          int64        `json:"message_id"`
	ChannelID          int64        `json:"channel_id"`
}

func (q *Queries) GetPollEntriesFromMessageID(ctx context.Context, arg GetPollEntriesFromMessageIDParams) ([]*GetPollEntriesFromMessageIDRow, error) {
	rows, err := q.db.Query(ctx, GetPollEntriesFromMessageID, arg.GuildID, arg.ChannelID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPollEntriesFromMessageIDRow{}
	for rows.Next() {
		var i GetPollEntriesFromMessageIDRow
		if err := rows.Scan(
			&i.GuildPollEntryUuid,
			&i.PollUuid,
			&i.UserID,
			&i.OptionIndex,
			&i.CreatedAt,
			&i.PollUuid_2,
			&i.CreatedAt_2,
			&i.GuildID,
			&i.CreatedBy,
			&i.HasEnded,
			&i.IsSetup,
			&i.Title,
			&i.Description,
			&i.AccentColour,
			&i.ImageUrl,
			&i.StartTime,
			&i.EndTime,
			&i.PollOptions,
			&i.IsAnonymous,
			&i.MaximumSelections,
			&i.Resubmissions,
			&i.ResultsVisibility,
			&i.RolesAllowed,
			&i.RolesExcluded,
			&i.MinimumJoinDate,
			&i.MessageID,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPollEntryUsers = `-- name: GetPollEntryUsers :many
SELECT DISTINCT user_id FROM guild_polls_entries
WHERE poll_uuid = $1
`

func (q *Queries) GetPollEntryUsers(ctx context.Context, pollUuid uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, GetPollEntryUsers, pollUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemovePollEntriesNotMatching = `-- name: RemovePollEntriesNotMatching :exec
DELETE FROM guild_polls_entries
WHERE poll_uuid = $1 AND user_id = $2 AND option_index NOT IN ($3)
`

type RemovePollEntriesNotMatchingParams struct {
	PollUuid    uuid.UUID `json:"poll_uuid"`
	UserID      int64     `json:"user_id"`
	OptionIndex int32     `json:"option_index"`
}

func (q *Queries) RemovePollEntriesNotMatching(ctx context.Context, arg RemovePollEntriesNotMatchingParams) error {
	_, err := q.db.Exec(ctx, RemovePollEntriesNotMatching, arg.PollUuid, arg.UserID, arg.OptionIndex)
	return err
}
