// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: guild_settings_autoroles_query.sql

package database

import (
	"context"
)

const CreateAutoRolesGuildSettings = `-- name: CreateAutoRolesGuildSettings :one
INSERT INTO guild_settings_autoroles (guild_id, toggle_enabled, roles)
    VALUES ($1, $2, $3)
RETURNING
    guild_id, toggle_enabled, roles
`

type CreateAutoRolesGuildSettingsParams struct {
	GuildID       int64   `json:"guild_id"`
	ToggleEnabled bool    `json:"toggle_enabled"`
	Roles         []int64 `json:"roles"`
}

func (q *Queries) CreateAutoRolesGuildSettings(ctx context.Context, arg *CreateAutoRolesGuildSettingsParams) (*GuildSettingsAutoroles, error) {
	row := q.db.QueryRow(ctx, CreateAutoRolesGuildSettings, arg.GuildID, arg.ToggleEnabled, arg.Roles)
	var i GuildSettingsAutoroles
	err := row.Scan(&i.GuildID, &i.ToggleEnabled, &i.Roles)
	return &i, err
}

const CreateOrUpdateAutoRolesGuildSettings = `-- name: CreateOrUpdateAutoRolesGuildSettings :one
INSERT INTO guild_settings_autoroles (guild_id, toggle_enabled, roles)
    VALUES ($1, $2, $3)
ON CONFLICT(guild_id) DO UPDATE
    SET toggle_enabled = EXCLUDED.toggle_enabled,
        roles = EXCLUDED.roles
RETURNING
    guild_id, toggle_enabled, roles
`

type CreateOrUpdateAutoRolesGuildSettingsParams struct {
	GuildID       int64   `json:"guild_id"`
	ToggleEnabled bool    `json:"toggle_enabled"`
	Roles         []int64 `json:"roles"`
}

func (q *Queries) CreateOrUpdateAutoRolesGuildSettings(ctx context.Context, arg *CreateOrUpdateAutoRolesGuildSettingsParams) (*GuildSettingsAutoroles, error) {
	row := q.db.QueryRow(ctx, CreateOrUpdateAutoRolesGuildSettings, arg.GuildID, arg.ToggleEnabled, arg.Roles)
	var i GuildSettingsAutoroles
	err := row.Scan(&i.GuildID, &i.ToggleEnabled, &i.Roles)
	return &i, err
}

const GetAutoRolesGuildSettings = `-- name: GetAutoRolesGuildSettings :one
SELECT
    guild_id, toggle_enabled, roles
FROM
    guild_settings_autoroles
WHERE
    guild_id = $1
`

func (q *Queries) GetAutoRolesGuildSettings(ctx context.Context, guildID int64) (*GuildSettingsAutoroles, error) {
	row := q.db.QueryRow(ctx, GetAutoRolesGuildSettings, guildID)
	var i GuildSettingsAutoroles
	err := row.Scan(&i.GuildID, &i.ToggleEnabled, &i.Roles)
	return &i, err
}

const UpdateAutoRolesGuildSettings = `-- name: UpdateAutoRolesGuildSettings :execrows
UPDATE
    guild_settings_autoroles
SET
    toggle_enabled = $2,
    roles = $3
WHERE
    guild_id = $1
`

type UpdateAutoRolesGuildSettingsParams struct {
	GuildID       int64   `json:"guild_id"`
	ToggleEnabled bool    `json:"toggle_enabled"`
	Roles         []int64 `json:"roles"`
}

func (q *Queries) UpdateAutoRolesGuildSettings(ctx context.Context, arg *UpdateAutoRolesGuildSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, UpdateAutoRolesGuildSettings, arg.GuildID, arg.ToggleEnabled, arg.Roles)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
