// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_giveaways_query.sql

package database

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
)

const CreateGiveaway = `-- name: CreateGiveaway :one
INSERT INTO guild_giveaways (giveaway_uuid, created_at, guild_id, created_by, is_setup, title, description, end_time, start_time, announce_winners, giveaway_prizes, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id, accent_colour, image_url, show_prizes, show_entries)
VALUES (uuid_generate_v7(), NOW(), $1, $2, TRUE, $3, $4, $5, NOW(), TRUE, '[]', '[]', '[]', 'epoch', 0, 0, -1, '', TRUE, TRUE)
RETURNING
    giveaway_uuid, created_at, guild_id, created_by, is_setup, title, description, accent_colour, image_url, start_time, end_time, announce_winners, giveaway_prizes, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id, show_prizes, show_entries
`

type CreateGiveawayParams struct {
	GuildID     int64     `json:"guild_id"`
	CreatedBy   int64     `json:"created_by"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	EndTime     time.Time `json:"end_time"`
}

func (q *Queries) CreateGiveaway(ctx context.Context, arg CreateGiveawayParams) (*GuildGiveaways, error) {
	row := q.db.QueryRow(ctx, CreateGiveaway,
		arg.GuildID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.EndTime,
	)
	var i GuildGiveaways
	err := row.Scan(
		&i.GiveawayUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.AnnounceWinners,
		&i.GiveawayPrizes,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
		&i.ShowPrizes,
		&i.ShowEntries,
	)
	return &i, err
}

const GetGiveaway = `-- name: GetGiveaway :one
SELECT
    giveaway_uuid, created_at, guild_id, created_by, is_setup, title, description, accent_colour, image_url, start_time, end_time, announce_winners, giveaway_prizes, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id, show_prizes, show_entries
FROM
    guild_giveaways
WHERE
    guild_id = $1
    AND giveaway_uuid = $2
`

type GetGiveawayParams struct {
	GuildID      int64     `json:"guild_id"`
	GiveawayUuid uuid.UUID `json:"giveaway_uuid"`
}

func (q *Queries) GetGiveaway(ctx context.Context, arg GetGiveawayParams) (*GuildGiveaways, error) {
	row := q.db.QueryRow(ctx, GetGiveaway, arg.GuildID, arg.GiveawayUuid)
	var i GuildGiveaways
	err := row.Scan(
		&i.GiveawayUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.AnnounceWinners,
		&i.GiveawayPrizes,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
		&i.ShowPrizes,
		&i.ShowEntries,
	)
	return &i, err
}

const UpdateGiveaway = `-- name: UpdateGiveaway :one
UPDATE
    guild_giveaways
SET
    is_setup = $2,
    title = $3,
    description = $4,
    start_time = $5,
    end_time = $6,
    announce_winners = $7,
    giveaway_prizes = $8,
    roles_allowed = $9,
    roles_excluded = $10,
    minimum_join_date = $11,
    accent_colour = $12,
    image_url = $13,
    show_prizes = $14,
    show_entries = $15
WHERE
    giveaway_uuid = $1
RETURNING
    giveaway_uuid, created_at, guild_id, created_by, is_setup, title, description, accent_colour, image_url, start_time, end_time, announce_winners, giveaway_prizes, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id, show_prizes, show_entries
`

type UpdateGiveawayParams struct {
	GiveawayUuid    uuid.UUID    `json:"giveaway_uuid"`
	IsSetup         bool         `json:"is_setup"`
	Title           string       `json:"title"`
	Description     string       `json:"description"`
	StartTime       time.Time    `json:"start_time"`
	EndTime         time.Time    `json:"end_time"`
	AnnounceWinners bool         `json:"announce_winners"`
	GiveawayPrizes  pgtype.JSONB `json:"giveaway_prizes"`
	RolesAllowed    pgtype.JSONB `json:"roles_allowed"`
	RolesExcluded   pgtype.JSONB `json:"roles_excluded"`
	MinimumJoinDate time.Time    `json:"minimum_join_date"`
	AccentColour    int64        `json:"accent_colour"`
	ImageUrl        string       `json:"image_url"`
	ShowPrizes      bool         `json:"show_prizes"`
	ShowEntries     bool         `json:"show_entries"`
}

func (q *Queries) UpdateGiveaway(ctx context.Context, arg UpdateGiveawayParams) (*GuildGiveaways, error) {
	row := q.db.QueryRow(ctx, UpdateGiveaway,
		arg.GiveawayUuid,
		arg.IsSetup,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AnnounceWinners,
		arg.GiveawayPrizes,
		arg.RolesAllowed,
		arg.RolesExcluded,
		arg.MinimumJoinDate,
		arg.AccentColour,
		arg.ImageUrl,
		arg.ShowPrizes,
		arg.ShowEntries,
	)
	var i GuildGiveaways
	err := row.Scan(
		&i.GiveawayUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.AnnounceWinners,
		&i.GiveawayPrizes,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
		&i.ShowPrizes,
		&i.ShowEntries,
	)
	return &i, err
}

const UpdateGiveawayMessage = `-- name: UpdateGiveawayMessage :one
UPDATE
    guild_giveaways
SET
    message_id = $2,
    channel_id = $3
WHERE
    giveaway_uuid = $1
RETURNING
    giveaway_uuid, created_at, guild_id, created_by, is_setup, title, description, accent_colour, image_url, start_time, end_time, announce_winners, giveaway_prizes, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id, show_prizes, show_entries
`

type UpdateGiveawayMessageParams struct {
	GiveawayUuid uuid.UUID `json:"giveaway_uuid"`
	MessageID    int64     `json:"message_id"`
	ChannelID    int64     `json:"channel_id"`
}

func (q *Queries) UpdateGiveawayMessage(ctx context.Context, arg UpdateGiveawayMessageParams) (*GuildGiveaways, error) {
	row := q.db.QueryRow(ctx, UpdateGiveawayMessage, arg.GiveawayUuid, arg.MessageID, arg.ChannelID)
	var i GuildGiveaways
	err := row.Scan(
		&i.GiveawayUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.AnnounceWinners,
		&i.GiveawayPrizes,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
		&i.ShowPrizes,
		&i.ShowEntries,
	)
	return &i, err
}
