// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_settings_borderwall_query.sql

package database

import (
	"context"
	"database/sql"

	
	"github.com/jackc/pgtype"
)

const CreateBorderwallGuildSettings = `-- name: CreateBorderwallGuildSettings :one
INSERT INTO guild_settings_borderwall (guild_id, toggle_enabled, toggle_send_dm, channel, message_verify, message_verified, roles_on_join, roles_on_verify, moderation_checkup_uuid)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    guild_id, toggle_enabled, toggle_send_dm, channel, message_verify, message_verified, roles_on_join, roles_on_verify, moderation_checkup_uuid
`

type CreateBorderwallGuildSettingsParams struct {
	GuildID               int64         `json:"guild_id"`
	ToggleEnabled         bool          `json:"toggle_enabled"`
	ToggleSendDm          bool          `json:"toggle_send_dm"`
	Channel               int64         `json:"channel"`
	MessageVerify         pgtype.JSONB  `json:"message_verify"`
	MessageVerified       pgtype.JSONB  `json:"message_verified"`
	RolesOnJoin           []int64       `json:"roles_on_join"`
	RolesOnVerify         []int64       `json:"roles_on_verify"`
	ModerationCheckupUuid uuid.NullUUID `json:"moderation_checkup_uuid"`
}

func (q *Queries) CreateBorderwallGuildSettings(ctx context.Context, arg CreateBorderwallGuildSettingsParams) (*GuildSettingsBorderwall, error) {
	row := q.db.QueryRow(ctx, CreateBorderwallGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.ToggleSendDm,
		arg.Channel,
		arg.MessageVerify,
		arg.MessageVerified,
		arg.RolesOnJoin,
		arg.RolesOnVerify,
		arg.ModerationCheckupUuid,
	)
	var i GuildSettingsBorderwall
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.ToggleSendDm,
		&i.Channel,
		&i.MessageVerify,
		&i.MessageVerified,
		&i.RolesOnJoin,
		&i.RolesOnVerify,
		&i.ModerationCheckupUuid,
	)
	return &i, err
}

const CreateOrUpdateBorderwallGuildSettings = `-- name: CreateOrUpdateBorderwallGuildSettings :one
INSERT INTO guild_settings_borderwall (guild_id, toggle_enabled, toggle_send_dm, channel, message_verify, message_verified, roles_on_join, roles_on_verify, moderation_checkup_uuid)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT(guild_id) DO UPDATE
    SET toggle_enabled = EXCLUDED.toggle_enabled, 
        toggle_send_dm = EXCLUDED.toggle_send_dm, 
        channel = EXCLUDED.channel, 
        message_verify = EXCLUDED.message_verify, 
        message_verified = EXCLUDED.message_verified, 
        roles_on_join = EXCLUDED.roles_on_join, 
        roles_on_verify = EXCLUDED.roles_on_verify,
        moderation_checkup_uuid = EXCLUDED.moderation_checkup_uuid
RETURNING
    guild_id, toggle_enabled, toggle_send_dm, channel, message_verify, message_verified, roles_on_join, roles_on_verify, moderation_checkup_uuid
`

type CreateOrUpdateBorderwallGuildSettingsParams struct {
	GuildID               int64         `json:"guild_id"`
	ToggleEnabled         bool          `json:"toggle_enabled"`
	ToggleSendDm          bool          `json:"toggle_send_dm"`
	Channel               int64         `json:"channel"`
	MessageVerify         pgtype.JSONB  `json:"message_verify"`
	MessageVerified       pgtype.JSONB  `json:"message_verified"`
	RolesOnJoin           []int64       `json:"roles_on_join"`
	RolesOnVerify         []int64       `json:"roles_on_verify"`
	ModerationCheckupUuid uuid.NullUUID `json:"moderation_checkup_uuid"`
}

func (q *Queries) CreateOrUpdateBorderwallGuildSettings(ctx context.Context, arg CreateOrUpdateBorderwallGuildSettingsParams) (*GuildSettingsBorderwall, error) {
	row := q.db.QueryRow(ctx, CreateOrUpdateBorderwallGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.ToggleSendDm,
		arg.Channel,
		arg.MessageVerify,
		arg.MessageVerified,
		arg.RolesOnJoin,
		arg.RolesOnVerify,
		arg.ModerationCheckupUuid,
	)
	var i GuildSettingsBorderwall
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.ToggleSendDm,
		&i.Channel,
		&i.MessageVerify,
		&i.MessageVerified,
		&i.RolesOnJoin,
		&i.RolesOnVerify,
		&i.ModerationCheckupUuid,
	)
	return &i, err
}

const GetBorderwallGuildSettings = `-- name: GetBorderwallGuildSettings :one
SELECT
    guild_settings_borderwall.guild_id, toggle_enabled, toggle_send_dm, channel, message_verify, message_verified, roles_on_join, roles_on_verify, moderation_checkup_uuid, checkup_uuid, moderation_checkup.guild_id, user_id, audit_type, started_at, completed_at, dom, inv, score_change, score_safe, score_question, score_explicit, is_blocked
FROM
    guild_settings_borderwall
    LEFT JOIN moderation_checkup ON guild_settings_borderwall.moderation_checkup_uuid = moderation_checkup.checkup_uuid
WHERE
    guild_settings_borderwall.guild_id = $1
`

type GetBorderwallGuildSettingsRow struct {
	GuildID               int64           `json:"guild_id"`
	ToggleEnabled         bool            `json:"toggle_enabled"`
	ToggleSendDm          bool            `json:"toggle_send_dm"`
	Channel               int64           `json:"channel"`
	MessageVerify         pgtype.JSONB    `json:"message_verify"`
	MessageVerified       pgtype.JSONB    `json:"message_verified"`
	RolesOnJoin           []int64         `json:"roles_on_join"`
	RolesOnVerify         []int64         `json:"roles_on_verify"`
	ModerationCheckupUuid uuid.NullUUID   `json:"moderation_checkup_uuid"`
	CheckupUuid           uuid.NullUUID   `json:"checkup_uuid"`
	GuildID_2             sql.NullInt64   `json:"guild_id_2"`
	UserID                sql.NullInt64   `json:"user_id"`
	AuditType             sql.NullInt32   `json:"audit_type"`
	StartedAt             sql.NullTime    `json:"started_at"`
	CompletedAt           sql.NullTime    `json:"completed_at"`
	Dom                   pgtype.JSONB    `json:"dom"`
	Inv                   pgtype.JSONB    `json:"inv"`
	ScoreChange           sql.NullFloat64 `json:"score_change"`
	ScoreSafe             sql.NullFloat64 `json:"score_safe"`
	ScoreQuestion         sql.NullFloat64 `json:"score_question"`
	ScoreExplicit         sql.NullFloat64 `json:"score_explicit"`
	IsBlocked             sql.NullBool    `json:"is_blocked"`
}

func (q *Queries) GetBorderwallGuildSettings(ctx context.Context, guildID int64) (*GetBorderwallGuildSettingsRow, error) {
	row := q.db.QueryRow(ctx, GetBorderwallGuildSettings, guildID)
	var i GetBorderwallGuildSettingsRow
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.ToggleSendDm,
		&i.Channel,
		&i.MessageVerify,
		&i.MessageVerified,
		&i.RolesOnJoin,
		&i.RolesOnVerify,
		&i.ModerationCheckupUuid,
		&i.CheckupUuid,
		&i.GuildID_2,
		&i.UserID,
		&i.AuditType,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Dom,
		&i.Inv,
		&i.ScoreChange,
		&i.ScoreSafe,
		&i.ScoreQuestion,
		&i.ScoreExplicit,
		&i.IsBlocked,
	)
	return &i, err
}

const UpdateBorderwallGuildSettings = `-- name: UpdateBorderwallGuildSettings :execrows
UPDATE
    guild_settings_borderwall
SET
    toggle_enabled = $2,
    toggle_send_dm = $3,
    channel = $4,
    message_verify = $5,
    message_verified = $6,
    roles_on_join = $7,
    roles_on_verify = $8,
    moderation_checkup_uuid = $9
WHERE
    guild_id = $1
`

type UpdateBorderwallGuildSettingsParams struct {
	GuildID               int64         `json:"guild_id"`
	ToggleEnabled         bool          `json:"toggle_enabled"`
	ToggleSendDm          bool          `json:"toggle_send_dm"`
	Channel               int64         `json:"channel"`
	MessageVerify         pgtype.JSONB  `json:"message_verify"`
	MessageVerified       pgtype.JSONB  `json:"message_verified"`
	RolesOnJoin           []int64       `json:"roles_on_join"`
	RolesOnVerify         []int64       `json:"roles_on_verify"`
	ModerationCheckupUuid uuid.NullUUID `json:"moderation_checkup_uuid"`
}

func (q *Queries) UpdateBorderwallGuildSettings(ctx context.Context, arg UpdateBorderwallGuildSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, UpdateBorderwallGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.ToggleSendDm,
		arg.Channel,
		arg.MessageVerify,
		arg.MessageVerified,
		arg.RolesOnJoin,
		arg.RolesOnVerify,
		arg.ModerationCheckupUuid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
