// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_giveaways_query.sql

package database

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
)

const CreateGiveaway = `-- name: CreateGiveaway :one
INSERT INTO guild_giveaways (giveaway_uuid, created_at, guild_id, created_by, is_setup, title, end_time, start_time, announce_winners, giveaway_prizes, roles_allowed, roles_excluded, minimum_join_date)
VALUES (uuid_generate_v7(), NOW(), $1, $2, FALSE, $3, $4, NOW(), TRUE, '[]', '[]', '[]', 'epoch')
RETURNING
    giveaway_uuid, created_at, guild_id, created_by, is_setup, title, start_time, end_time, announce_winners, giveaway_prizes, roles_allowed, roles_excluded, minimum_join_date
`

type CreateGiveawayParams struct {
	GuildID   int64     `json:"guild_id"`
	CreatedBy int64     `json:"created_by"`
	Title     string    `json:"title"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) CreateGiveaway(ctx context.Context, arg CreateGiveawayParams) (*GuildGiveaways, error) {
	row := q.db.QueryRow(ctx, CreateGiveaway,
		arg.GuildID,
		arg.CreatedBy,
		arg.Title,
		arg.EndTime,
	)
	var i GuildGiveaways
	err := row.Scan(
		&i.GiveawayUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.IsSetup,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.AnnounceWinners,
		&i.GiveawayPrizes,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
	)
	return &i, err
}

const GetGiveaway = `-- name: GetGiveaway :one
SELECT
    giveaway_uuid, created_at, guild_id, created_by, is_setup, title, start_time, end_time, announce_winners, giveaway_prizes, roles_allowed, roles_excluded, minimum_join_date
FROM
    guild_giveaways
WHERE
    guild_id = $1
    AND giveaway_uuid = $2
`

type GetGiveawayParams struct {
	GuildID      int64     `json:"guild_id"`
	GiveawayUuid uuid.UUID `json:"giveaway_uuid"`
}

func (q *Queries) GetGiveaway(ctx context.Context, arg GetGiveawayParams) (*GuildGiveaways, error) {
	row := q.db.QueryRow(ctx, GetGiveaway, arg.GuildID, arg.GiveawayUuid)
	var i GuildGiveaways
	err := row.Scan(
		&i.GiveawayUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.IsSetup,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.AnnounceWinners,
		&i.GiveawayPrizes,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
	)
	return &i, err
}

const UpdateGiveaway = `-- name: UpdateGiveaway :one
UPDATE
    guild_giveaways
SET
    is_setup = $2,
    title = $3,
    start_time = $4,
    end_time = $5,
    announce_winners = $6,
    giveaway_prizes = $7,
    roles_allowed = $8,
    roles_excluded = $9,
    minimum_join_date = $10
WHERE
    giveaway_uuid = $1
RETURNING
    giveaway_uuid, created_at, guild_id, created_by, is_setup, title, start_time, end_time, announce_winners, giveaway_prizes, roles_allowed, roles_excluded, minimum_join_date
`

type UpdateGiveawayParams struct {
	GiveawayUuid    uuid.UUID    `json:"giveaway_uuid"`
	IsSetup         bool         `json:"is_setup"`
	Title           string       `json:"title"`
	StartTime       time.Time    `json:"start_time"`
	EndTime         time.Time    `json:"end_time"`
	AnnounceWinners bool         `json:"announce_winners"`
	GiveawayPrizes  pgtype.JSONB `json:"giveaway_prizes"`
	RolesAllowed    pgtype.JSONB `json:"roles_allowed"`
	RolesExcluded   pgtype.JSONB `json:"roles_excluded"`
	MinimumJoinDate time.Time    `json:"minimum_join_date"`
}

func (q *Queries) UpdateGiveaway(ctx context.Context, arg UpdateGiveawayParams) (*GuildGiveaways, error) {
	row := q.db.QueryRow(ctx, UpdateGiveaway,
		arg.GiveawayUuid,
		arg.IsSetup,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.AnnounceWinners,
		arg.GiveawayPrizes,
		arg.RolesAllowed,
		arg.RolesExcluded,
		arg.MinimumJoinDate,
	)
	var i GuildGiveaways
	err := row.Scan(
		&i.GiveawayUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.IsSetup,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.AnnounceWinners,
		&i.GiveawayPrizes,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
	)
	return &i, err
}
