// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_voice_channel_open_sessions_query.sql

package database

import (
	"context"
	"time"
)

const CreateGuildVoiceChannelOpenSession = `-- name: CreateGuildVoiceChannelOpenSession :exec
INSERT INTO guild_voice_channel_open_sessions (guild_id, user_id, channel_id, start_ts, last_seen_ts)
VALUES ($1, $2, $3, $4, $5)
`

type CreateGuildVoiceChannelOpenSessionParams struct {
	GuildID    int64     `json:"guild_id"`
	UserID     int64     `json:"user_id"`
	ChannelID  int64     `json:"channel_id"`
	StartTs    time.Time `json:"start_ts"`
	LastSeenTs time.Time `json:"last_seen_ts"`
}

func (q *Queries) CreateGuildVoiceChannelOpenSession(ctx context.Context, arg CreateGuildVoiceChannelOpenSessionParams) error {
	_, err := q.db.Exec(ctx, CreateGuildVoiceChannelOpenSession,
		arg.GuildID,
		arg.UserID,
		arg.ChannelID,
		arg.StartTs,
		arg.LastSeenTs,
	)
	return err
}

const DeleteAndGetGuildVoiceChannelOpenSession = `-- name: DeleteAndGetGuildVoiceChannelOpenSession :one
DELETE FROM guild_voice_channel_open_sessions
WHERE guild_id = $1 AND user_id = $2
RETURNING guild_id, user_id, channel_id, start_ts, last_seen_ts
`

type DeleteAndGetGuildVoiceChannelOpenSessionParams struct {
	GuildID int64 `json:"guild_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) DeleteAndGetGuildVoiceChannelOpenSession(ctx context.Context, arg DeleteAndGetGuildVoiceChannelOpenSessionParams) (*GuildVoiceChannelOpenSessions, error) {
	row := q.db.QueryRow(ctx, DeleteAndGetGuildVoiceChannelOpenSession, arg.GuildID, arg.UserID)
	var i GuildVoiceChannelOpenSessions
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.ChannelID,
		&i.StartTs,
		&i.LastSeenTs,
	)
	return &i, err
}

const DeleteAndGetGuildVoiceChannelOpenSessionsBefore = `-- name: DeleteAndGetGuildVoiceChannelOpenSessionsBefore :many
DELETE FROM guild_voice_channel_open_sessions
WHERE last_seen_ts < $1
RETURNING guild_id, user_id, channel_id, start_ts, last_seen_ts
`

func (q *Queries) DeleteAndGetGuildVoiceChannelOpenSessionsBefore(ctx context.Context, lastSeenTs time.Time) ([]*GuildVoiceChannelOpenSessions, error) {
	rows, err := q.db.Query(ctx, DeleteAndGetGuildVoiceChannelOpenSessionsBefore, lastSeenTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GuildVoiceChannelOpenSessions{}
	for rows.Next() {
		var i GuildVoiceChannelOpenSessions
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.ChannelID,
			&i.StartTs,
			&i.LastSeenTs,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateGuildVoiceChannelOpenSessionLastSeen = `-- name: UpdateGuildVoiceChannelOpenSessionLastSeen :exec
UPDATE guild_voice_channel_open_sessions
SET last_seen_ts = $3
WHERE guild_id = $1 AND user_id = $2
`

type UpdateGuildVoiceChannelOpenSessionLastSeenParams struct {
	GuildID    int64     `json:"guild_id"`
	UserID     int64     `json:"user_id"`
	LastSeenTs time.Time `json:"last_seen_ts"`
}

func (q *Queries) UpdateGuildVoiceChannelOpenSessionLastSeen(ctx context.Context, arg UpdateGuildVoiceChannelOpenSessionLastSeenParams) error {
	_, err := q.db.Exec(ctx, UpdateGuildVoiceChannelOpenSessionLastSeen, arg.GuildID, arg.UserID, arg.LastSeenTs)
	return err
}
