/// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_voice_channel_stats_query.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const CreateVoiceChannelStat = `-- name: CreateVoiceChannelStat :exec
INSERT INTO guild_voice_channel_stats (guild_id, channel_id, user_id, start_ts, end_ts, total_time_ms)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateVoiceChannelStatParams struct {
	GuildID     int64     `json:"guild_id"`
	ChannelID   int64     `json:"channel_id"`
	UserID      int64     `json:"user_id"`
	StartTs     time.Time `json:"start_ts"`
	EndTs       time.Time `json:"end_ts"`
	TotalTimeMs int64     `json:"total_time_ms"`
}

func (q *Queries) CreateVoiceChannelStat(ctx context.Context, arg CreateVoiceChannelStatParams) error {
	_, err := q.db.Exec(ctx, CreateVoiceChannelStat,
		arg.GuildID,
		arg.ChannelID,
		arg.UserID,
		arg.StartTs,
		arg.EndTs,
		arg.TotalTimeMs,
	)
	return err
}

const DeleteOpenVoiceChannelSession = `-- name: DeleteOpenVoiceChannelSession :exec
DELETE FROM guild_voice_channel_open_sessions
WHERE guild_id = $1 AND user_id = $2
`

type DeleteOpenVoiceChannelSessionParams struct {
	GuildID int64 `json:"guild_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) DeleteOpenVoiceChannelSession(ctx context.Context, arg DeleteOpenVoiceChannelSessionParams) error {
	_, err := q.db.Exec(ctx, DeleteOpenVoiceChannelSession, arg.GuildID, arg.UserID)
	return err
}

const FetchVoiceChannelEventsForAggregation = `-- name: FetchVoiceChannelEventsForAggregation :many
SELECT 
    guild_id,
    user_id,
    channel_id,
    event_type,
    occurred_at
FROM ingest_voice_channel_events
WHERE occurred_at > $1 AND occurred_at <= $2
ORDER BY user_id, occurred_at
`

type FetchVoiceChannelEventsForAggregationParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

type FetchVoiceChannelEventsForAggregationRow struct {
	GuildID    int64         `json:"guild_id"`
	UserID     int64         `json:"user_id"`
	ChannelID  sql.NullInt64 `json:"channel_id"`
	EventType  int16         `json:"event_type"`
	OccurredAt time.Time     `json:"occurred_at"`
}

func (q *Queries) FetchVoiceChannelEventsForAggregation(ctx context.Context, arg FetchVoiceChannelEventsForAggregationParams) ([]*FetchVoiceChannelEventsForAggregationRow, error) {
	rows, err := q.db.Query(ctx, FetchVoiceChannelEventsForAggregation, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FetchVoiceChannelEventsForAggregationRow{}
	for rows.Next() {
		var i FetchVoiceChannelEventsForAggregationRow
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.ChannelID,
			&i.EventType,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllOpenVoiceChannelSessions = `-- name: GetAllOpenVoiceChannelSessions :many
SELECT 
    guild_id,
    user_id,
    channel_id,
    start_ts,
    last_seen_ts
FROM guild_voice_channel_open_sessions
`

func (q *Queries) GetAllOpenVoiceChannelSessions(ctx context.Context) ([]*GuildVoiceChannelOpenSessions, error) {
	rows, err := q.db.Query(ctx, GetAllOpenVoiceChannelSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GuildVoiceChannelOpenSessions{}
	for rows.Next() {
		var i GuildVoiceChannelOpenSessions
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.ChannelID,
			&i.StartTs,
			&i.LastSeenTs,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOpenVoiceChannelSession = `-- name: GetOpenVoiceChannelSession :one
SELECT 
    guild_id,
    user_id,
    channel_id,
    start_ts,
    last_seen_ts
FROM guild_voice_channel_open_sessions
WHERE guild_id = $1 AND user_id = $2
`

type GetOpenVoiceChannelSessionParams struct {
	GuildID int64 `json:"guild_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GetOpenVoiceChannelSession(ctx context.Context, arg GetOpenVoiceChannelSessionParams) (*GuildVoiceChannelOpenSessions, error) {
	row := q.db.QueryRow(ctx, GetOpenVoiceChannelSession, arg.GuildID, arg.UserID)
	var i GuildVoiceChannelOpenSessions
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.ChannelID,
		&i.StartTs,
		&i.LastSeenTs,
	)
	return &i, err
}

const UpsertOpenVoiceChannelSession = `-- name: UpsertOpenVoiceChannelSession :exec
INSERT INTO guild_voice_channel_open_sessions (guild_id, user_id, channel_id, start_ts, last_seen_ts)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (guild_id, user_id) DO UPDATE SET
    channel_id = EXCLUDED.channel_id,
    last_seen_ts = EXCLUDED.last_seen_ts
`

type UpsertOpenVoiceChannelSessionParams struct {
	GuildID    int64     `json:"guild_id"`
	UserID     int64     `json:"user_id"`
	ChannelID  int64     `json:"channel_id"`
	StartTs    time.Time `json:"start_ts"`
	LastSeenTs time.Time `json:"last_seen_ts"`
}

func (q *Queries) UpsertOpenVoiceChannelSession(ctx context.Context, arg UpsertOpenVoiceChannelSessionParams) error {
	_, err := q.db.Exec(ctx, UpsertOpenVoiceChannelSession,
		arg.GuildID,
		arg.UserID,
		arg.ChannelID,
		arg.StartTs,
		arg.LastSeenTs,
	)
	return err
}
