// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_giveaways_entries_query.sql

package database

import (
	"context"

	"github.com/gofrs/uuid"
)

const AddGiveawayEntry = `-- name: AddGiveawayEntry :exec
INSERT INTO guild_giveaways_entries (guild_giveaway_entry_uuid, giveaway_uuid, user_id, created_at)
VALUES (uuid_generate_v7(), $1, $2, NOW())
`

type AddGiveawayEntryParams struct {
	GiveawayUuid uuid.UUID `json:"giveaway_uuid"`
	UserID       int64     `json:"user_id"`
}

func (q *Queries) AddGiveawayEntry(ctx context.Context, arg AddGiveawayEntryParams) error {
	_, err := q.db.Exec(ctx, AddGiveawayEntry, arg.GiveawayUuid, arg.UserID)
	return err
}

const RemoveGiveawayEntry = `-- name: RemoveGiveawayEntry :exec
DELETE FROM guild_giveaways_entries
WHERE giveaway_uuid = $1 AND user_id = $2
`

type RemoveGiveawayEntryParams struct {
	GiveawayUuid uuid.UUID `json:"giveaway_uuid"`
	UserID       int64     `json:"user_id"`
}

func (q *Queries) RemoveGiveawayEntry(ctx context.Context, arg RemoveGiveawayEntryParams) error {
	_, err := q.db.Exec(ctx, RemoveGiveawayEntry, arg.GiveawayUuid, arg.UserID)
	return err
}
