// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_voice_channel_stats_query.sql

package database

import (
	"context"
	"time"
)

const CreateVoiceChannelStat = `-- name: CreateVoiceChannelStat :exec
INSERT INTO guild_voice_channel_stats (guild_id, channel_id, user_id, start_ts, end_ts, total_time_ms)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateVoiceChannelStatParams struct {
	GuildID     int64     `json:"guild_id"`
	ChannelID   int64     `json:"channel_id"`
	UserID      int64     `json:"user_id"`
	StartTs     time.Time `json:"start_ts"`
	EndTs       time.Time `json:"end_ts"`
	TotalTimeMs int64     `json:"total_time_ms"`
}

func (q *Queries) CreateVoiceChannelStat(ctx context.Context, arg CreateVoiceChannelStatParams) error {
	_, err := q.db.Exec(ctx, CreateVoiceChannelStat,
		arg.GuildID,
		arg.ChannelID,
		arg.UserID,
		arg.StartTs,
		arg.EndTs,
		arg.TotalTimeMs,
	)
	return err
}
