// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_settings_welcomer_dms_query.sql

package database

import (
	"context"
	"database/sql"

	
	"github.com/jackc/pgtype"
)

const CreateOrUpdateWelcomerDMsGuildSettings = `-- name: CreateOrUpdateWelcomerDMsGuildSettings :one
INSERT INTO guild_settings_welcomer_dms (guild_id, toggle_enabled, toggle_use_text_format, toggle_include_image, message_format, moderation_checkup_uuid)
    VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(guild_id) DO UPDATE
    SET toggle_enabled = EXCLUDED.toggle_enabled, 
        toggle_use_text_format = EXCLUDED.toggle_use_text_format, 
        toggle_include_image = EXCLUDED.toggle_include_image, 
        message_format = EXCLUDED.message_format,
        moderation_checkup_uuid = EXCLUDED.moderation_checkup_uuid
RETURNING
    guild_id, toggle_enabled, toggle_use_text_format, toggle_include_image, message_format, moderation_checkup_uuid
`

type CreateOrUpdateWelcomerDMsGuildSettingsParams struct {
	GuildID               int64         `json:"guild_id"`
	ToggleEnabled         bool          `json:"toggle_enabled"`
	ToggleUseTextFormat   bool          `json:"toggle_use_text_format"`
	ToggleIncludeImage    bool          `json:"toggle_include_image"`
	MessageFormat         pgtype.JSONB  `json:"message_format"`
	ModerationCheckupUuid uuid.NullUUID `json:"moderation_checkup_uuid"`
}

func (q *Queries) CreateOrUpdateWelcomerDMsGuildSettings(ctx context.Context, arg CreateOrUpdateWelcomerDMsGuildSettingsParams) (*GuildSettingsWelcomerDms, error) {
	row := q.db.QueryRow(ctx, CreateOrUpdateWelcomerDMsGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.ToggleUseTextFormat,
		arg.ToggleIncludeImage,
		arg.MessageFormat,
		arg.ModerationCheckupUuid,
	)
	var i GuildSettingsWelcomerDms
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.ToggleUseTextFormat,
		&i.ToggleIncludeImage,
		&i.MessageFormat,
		&i.ModerationCheckupUuid,
	)
	return &i, err
}

const CreateWelcomerDMsGuildSettings = `-- name: CreateWelcomerDMsGuildSettings :one
INSERT INTO guild_settings_welcomer_dms (guild_id, toggle_enabled, toggle_use_text_format, toggle_include_image, message_format, moderation_checkup_uuid)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    guild_id, toggle_enabled, toggle_use_text_format, toggle_include_image, message_format, moderation_checkup_uuid
`

type CreateWelcomerDMsGuildSettingsParams struct {
	GuildID               int64         `json:"guild_id"`
	ToggleEnabled         bool          `json:"toggle_enabled"`
	ToggleUseTextFormat   bool          `json:"toggle_use_text_format"`
	ToggleIncludeImage    bool          `json:"toggle_include_image"`
	MessageFormat         pgtype.JSONB  `json:"message_format"`
	ModerationCheckupUuid uuid.NullUUID `json:"moderation_checkup_uuid"`
}

func (q *Queries) CreateWelcomerDMsGuildSettings(ctx context.Context, arg CreateWelcomerDMsGuildSettingsParams) (*GuildSettingsWelcomerDms, error) {
	row := q.db.QueryRow(ctx, CreateWelcomerDMsGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.ToggleUseTextFormat,
		arg.ToggleIncludeImage,
		arg.MessageFormat,
		arg.ModerationCheckupUuid,
	)
	var i GuildSettingsWelcomerDms
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.ToggleUseTextFormat,
		&i.ToggleIncludeImage,
		&i.MessageFormat,
		&i.ModerationCheckupUuid,
	)
	return &i, err
}

const GetWelcomerDMsGuildSettings = `-- name: GetWelcomerDMsGuildSettings :one
SELECT
    guild_settings_welcomer_dms.guild_id, toggle_enabled, toggle_use_text_format, toggle_include_image, message_format, moderation_checkup_uuid, checkup_uuid, moderation_checkup.guild_id, user_id, audit_type, started_at, completed_at, dom, inv, score_change, score_safe, score_question, score_explicit, is_blocked
FROM
    guild_settings_welcomer_dms
    LEFT JOIN moderation_checkup ON guild_settings_welcomer_dms.moderation_checkup_uuid = moderation_checkup.checkup_uuid
WHERE
    guild_settings_welcomer_dms.guild_id = $1
`

type GetWelcomerDMsGuildSettingsRow struct {
	GuildID               int64           `json:"guild_id"`
	ToggleEnabled         bool            `json:"toggle_enabled"`
	ToggleUseTextFormat   bool            `json:"toggle_use_text_format"`
	ToggleIncludeImage    bool            `json:"toggle_include_image"`
	MessageFormat         pgtype.JSONB    `json:"message_format"`
	ModerationCheckupUuid uuid.NullUUID   `json:"moderation_checkup_uuid"`
	CheckupUuid           uuid.NullUUID   `json:"checkup_uuid"`
	GuildID_2             sql.NullInt64   `json:"guild_id_2"`
	UserID                sql.NullInt64   `json:"user_id"`
	AuditType             sql.NullInt32   `json:"audit_type"`
	StartedAt             sql.NullTime    `json:"started_at"`
	CompletedAt           sql.NullTime    `json:"completed_at"`
	Dom                   pgtype.JSONB    `json:"dom"`
	Inv                   pgtype.JSONB    `json:"inv"`
	ScoreChange           sql.NullFloat64 `json:"score_change"`
	ScoreSafe             sql.NullFloat64 `json:"score_safe"`
	ScoreQuestion         sql.NullFloat64 `json:"score_question"`
	ScoreExplicit         sql.NullFloat64 `json:"score_explicit"`
	IsBlocked             sql.NullBool    `json:"is_blocked"`
}

func (q *Queries) GetWelcomerDMsGuildSettings(ctx context.Context, guildID int64) (*GetWelcomerDMsGuildSettingsRow, error) {
	row := q.db.QueryRow(ctx, GetWelcomerDMsGuildSettings, guildID)
	var i GetWelcomerDMsGuildSettingsRow
	err := row.Scan(
		&i.GuildID,
		&i.ToggleEnabled,
		&i.ToggleUseTextFormat,
		&i.ToggleIncludeImage,
		&i.MessageFormat,
		&i.ModerationCheckupUuid,
		&i.CheckupUuid,
		&i.GuildID_2,
		&i.UserID,
		&i.AuditType,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Dom,
		&i.Inv,
		&i.ScoreChange,
		&i.ScoreSafe,
		&i.ScoreQuestion,
		&i.ScoreExplicit,
		&i.IsBlocked,
	)
	return &i, err
}

const UpdateWelcomerDMsGuildSettings = `-- name: UpdateWelcomerDMsGuildSettings :execrows
UPDATE
    guild_settings_welcomer_dms
SET
    toggle_enabled = $2,
    toggle_use_text_format = $3,
    toggle_include_image = $4,
    message_format = $5,
    moderation_checkup_uuid = $6
WHERE
    guild_id = $1
`

type UpdateWelcomerDMsGuildSettingsParams struct {
	GuildID               int64         `json:"guild_id"`
	ToggleEnabled         bool          `json:"toggle_enabled"`
	ToggleUseTextFormat   bool          `json:"toggle_use_text_format"`
	ToggleIncludeImage    bool          `json:"toggle_include_image"`
	MessageFormat         pgtype.JSONB  `json:"message_format"`
	ModerationCheckupUuid uuid.NullUUID `json:"moderation_checkup_uuid"`
}

func (q *Queries) UpdateWelcomerDMsGuildSettings(ctx context.Context, arg UpdateWelcomerDMsGuildSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, UpdateWelcomerDMsGuildSettings,
		arg.GuildID,
		arg.ToggleEnabled,
		arg.ToggleUseTextFormat,
		arg.ToggleIncludeImage,
		arg.MessageFormat,
		arg.ModerationCheckupUuid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
