// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_giveaways_winner_query.sql

package database

import (
	"context"

	"github.com/gofrs/uuid"
)

const CreateGiveawayWinner = `-- name: CreateGiveawayWinner :one
INSERT INTO guild_giveaways_winners (giveaway_uuid, user_id, prize, message_id)
VALUES ($1, $2, $3, $4)
RETURNING
    giveaway_winner_uuid, giveaway_uuid, user_id, prize, message_id
`

type CreateGiveawayWinnerParams struct {
	GiveawayUuid uuid.UUID `json:"giveaway_uuid"`
	UserID       int64     `json:"user_id"`
	Prize        string    `json:"prize"`
	MessageID    int64     `json:"message_id"`
}

func (q *Queries) CreateGiveawayWinner(ctx context.Context, arg CreateGiveawayWinnerParams) (*GuildGiveawaysWinners, error) {
	row := q.db.QueryRow(ctx, CreateGiveawayWinner,
		arg.GiveawayUuid,
		arg.UserID,
		arg.Prize,
		arg.MessageID,
	)
	var i GuildGiveawaysWinners
	err := row.Scan(
		&i.GiveawayWinnerUuid,
		&i.GiveawayUuid,
		&i.UserID,
		&i.Prize,
		&i.MessageID,
	)
	return &i, err
}

const GetGiveawayWinners = `-- name: GetGiveawayWinners :many
SELECT
    giveaway_winner_uuid, giveaway_uuid, user_id, prize, message_id
FROM
    guild_giveaways_winners
WHERE
    giveaway_uuid = $1
`

func (q *Queries) GetGiveawayWinners(ctx context.Context, giveawayUuid uuid.UUID) ([]*GuildGiveawaysWinners, error) {
	rows, err := q.db.Query(ctx, GetGiveawayWinners, giveawayUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GuildGiveawaysWinners{}
	for rows.Next() {
		var i GuildGiveawaysWinners
		if err := rows.Scan(
			&i.GiveawayWinnerUuid,
			&i.GiveawayUuid,
			&i.UserID,
			&i.Prize,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateGiveawayWinnerMessageID = `-- name: UpdateGiveawayWinnerMessageID :one
UPDATE
    guild_giveaways_winners
SET
    message_id = $2
WHERE
    giveaway_winner_uuid = $1
RETURNING
    giveaway_winner_uuid, giveaway_uuid, user_id, prize, message_id
`

type UpdateGiveawayWinnerMessageIDParams struct {
	GiveawayWinnerUuid uuid.UUID `json:"giveaway_winner_uuid"`
	MessageID          int64     `json:"message_id"`
}

func (q *Queries) UpdateGiveawayWinnerMessageID(ctx context.Context, arg UpdateGiveawayWinnerMessageIDParams) (*GuildGiveawaysWinners, error) {
	row := q.db.QueryRow(ctx, UpdateGiveawayWinnerMessageID, arg.GiveawayWinnerUuid, arg.MessageID)
	var i GuildGiveawaysWinners
	err := row.Scan(
		&i.GiveawayWinnerUuid,
		&i.GiveawayUuid,
		&i.UserID,
		&i.Prize,
		&i.MessageID,
	)
	return &i, err
}

const UpdateGiveawayWinnerUserID = `-- name: UpdateGiveawayWinnerUserID :one
UPDATE
    guild_giveaways_winners
SET
    user_id = $2
WHERE
    giveaway_winner_uuid = $1
RETURNING
    giveaway_winner_uuid, giveaway_uuid, user_id, prize, message_id
`

type UpdateGiveawayWinnerUserIDParams struct {
	GiveawayWinnerUuid uuid.UUID `json:"giveaway_winner_uuid"`
	UserID             int64     `json:"user_id"`
}

func (q *Queries) UpdateGiveawayWinnerUserID(ctx context.Context, arg UpdateGiveawayWinnerUserIDParams) (*GuildGiveawaysWinners, error) {
	row := q.db.QueryRow(ctx, UpdateGiveawayWinnerUserID, arg.GiveawayWinnerUuid, arg.UserID)
	var i GuildGiveawaysWinners
	err := row.Scan(
		&i.GiveawayWinnerUuid,
		&i.GiveawayUuid,
		&i.UserID,
		&i.Prize,
		&i.MessageID,
	)
	return &i, err
}
