// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_polls_query.sql

package database

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
)

const CreatePoll = `-- name: CreatePoll :one
INSERT INTO guild_polls (poll_uuid, created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, poll_options, is_anonymous, maximum_selections, resubmissions, results_visibility, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id)
VALUES (uuid_generate_v7(), NOW(), $1, $2, FALSE, TRUE, '', '', -1, '', NOW(), $3, '[]', FALSE, 1, $4, $5, '[]', '[]', 'epoch', 0, 0)
RETURNING
    poll_uuid, created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, poll_options, is_anonymous, maximum_selections, resubmissions, results_visibility, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id
`

type CreatePollParams struct {
	GuildID           int64     `json:"guild_id"`
	CreatedBy         int64     `json:"created_by"`
	EndTime           time.Time `json:"end_time"`
	Resubmissions     string    `json:"resubmissions"`
	ResultsVisibility string    `json:"results_visibility"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (*GuildPolls, error) {
	row := q.db.QueryRow(ctx, CreatePoll,
		arg.GuildID,
		arg.CreatedBy,
		arg.EndTime,
		arg.Resubmissions,
		arg.ResultsVisibility,
	)
	var i GuildPolls
	err := row.Scan(
		&i.PollUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.HasEnded,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.PollOptions,
		&i.IsAnonymous,
		&i.MaximumSelections,
		&i.Resubmissions,
		&i.ResultsVisibility,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
	)
	return &i, err
}

const GetExpiredPolls = `-- name: GetExpiredPolls :many
SELECT
    poll_uuid, created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, poll_options, is_anonymous, maximum_selections, resubmissions, results_visibility, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id
FROM
    guild_polls
WHERE
    has_ended = FALSE
    AND is_setup = FALSE
    AND end_time <= NOW()
    AND end_time > 'epoch'
`

func (q *Queries) GetExpiredPolls(ctx context.Context) ([]*GuildPolls, error) {
	rows, err := q.db.Query(ctx, GetExpiredPolls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GuildPolls{}
	for rows.Next() {
		var i GuildPolls
		if err := rows.Scan(
			&i.PollUuid,
			&i.CreatedAt,
			&i.GuildID,
			&i.CreatedBy,
			&i.HasEnded,
			&i.IsSetup,
			&i.Title,
			&i.Description,
			&i.AccentColour,
			&i.ImageUrl,
			&i.StartTime,
			&i.EndTime,
			&i.PollOptions,
			&i.IsAnonymous,
			&i.MaximumSelections,
			&i.Resubmissions,
			&i.ResultsVisibility,
			&i.RolesAllowed,
			&i.RolesExcluded,
			&i.MinimumJoinDate,
			&i.MessageID,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPoll = `-- name: GetPoll :one
SELECT
    poll_uuid, created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, poll_options, is_anonymous, maximum_selections, resubmissions, results_visibility, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id
FROM
    guild_polls
WHERE
    guild_id = $1
    AND poll_uuid = $2
`

type GetPollParams struct {
	GuildID  int64     `json:"guild_id"`
	PollUuid uuid.UUID `json:"poll_uuid"`
}

func (q *Queries) GetPoll(ctx context.Context, arg GetPollParams) (*GuildPolls, error) {
	row := q.db.QueryRow(ctx, GetPoll, arg.GuildID, arg.PollUuid)
	var i GuildPolls
	err := row.Scan(
		&i.PollUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.HasEnded,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.PollOptions,
		&i.IsAnonymous,
		&i.MaximumSelections,
		&i.Resubmissions,
		&i.ResultsVisibility,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
	)
	return &i, err
}

const GetPollFromMessageID = `-- name: GetPollFromMessageID :one
SELECT
    poll_uuid, created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, poll_options, is_anonymous, maximum_selections, resubmissions, results_visibility, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id
FROM
    guild_polls
WHERE
    guild_id = $1
    AND channel_id = $2
    AND message_id = $3
`

type GetPollFromMessageIDParams struct {
	GuildID   int64 `json:"guild_id"`
	ChannelID int64 `json:"channel_id"`
	MessageID int64 `json:"message_id"`
}

func (q *Queries) GetPollFromMessageID(ctx context.Context, arg GetPollFromMessageIDParams) (*GuildPolls, error) {
	row := q.db.QueryRow(ctx, GetPollFromMessageID, arg.GuildID, arg.ChannelID, arg.MessageID)
	var i GuildPolls
	err := row.Scan(
		&i.PollUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.HasEnded,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.PollOptions,
		&i.IsAnonymous,
		&i.MaximumSelections,
		&i.Resubmissions,
		&i.ResultsVisibility,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
	)
	return &i, err
}

const SetPollEnded = `-- name: SetPollEnded :one
UPDATE
    guild_polls
SET
    has_ended = $2
WHERE
    poll_uuid = $1
RETURNING
    poll_uuid, created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, poll_options, is_anonymous, maximum_selections, resubmissions, results_visibility, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id
`

type SetPollEndedParams struct {
	PollUuid uuid.UUID `json:"poll_uuid"`
	HasEnded bool      `json:"has_ended"`
}

func (q *Queries) SetPollEnded(ctx context.Context, arg SetPollEndedParams) (*GuildPolls, error) {
	row := q.db.QueryRow(ctx, SetPollEnded, arg.PollUuid, arg.HasEnded)
	var i GuildPolls
	err := row.Scan(
		&i.PollUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.HasEnded,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.PollOptions,
		&i.IsAnonymous,
		&i.MaximumSelections,
		&i.Resubmissions,
		&i.ResultsVisibility,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
	)
	return &i, err
}

const UpdatePoll = `-- name: UpdatePoll :one
UPDATE
    guild_polls
SET
    is_setup = $2,
    has_ended = $3,
    title = $4,
    description = $5,
    accent_colour = $6,
    image_url = $7,
    start_time = $8,
    end_time = $9,
    poll_options = $10,
    is_anonymous = $11,
    maximum_selections = $12,
    resubmissions = $13,
    results_visibility = $14,
    roles_allowed = $15,
    roles_excluded = $16,
    minimum_join_date = $17,
    message_id = $18,
    channel_id = $19
WHERE
    poll_uuid = $1
RETURNING
    poll_uuid, created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, poll_options, is_anonymous, maximum_selections, resubmissions, results_visibility, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id
`

type UpdatePollParams struct {
	PollUuid          uuid.UUID    `json:"poll_uuid"`
	IsSetup           bool         `json:"is_setup"`
	HasEnded          bool         `json:"has_ended"`
	Title             string       `json:"title"`
	Description       string       `json:"description"`
	AccentColour      int64        `json:"accent_colour"`
	ImageUrl          string       `json:"image_url"`
	StartTime         time.Time    `json:"start_time"`
	EndTime           time.Time    `json:"end_time"`
	PollOptions       pgtype.JSONB `json:"poll_options"`
	IsAnonymous       bool         `json:"is_anonymous"`
	MaximumSelections int32        `json:"maximum_selections"`
	Resubmissions     string       `json:"resubmissions"`
	ResultsVisibility string       `json:"results_visibility"`
	RolesAllowed      pgtype.JSONB `json:"roles_allowed"`
	RolesExcluded     pgtype.JSONB `json:"roles_excluded"`
	MinimumJoinDate   time.Time    `json:"minimum_join_date"`
	MessageID         int64        `json:"message_id"`
	ChannelID         int64        `json:"channel_id"`
}

func (q *Queries) UpdatePoll(ctx context.Context, arg UpdatePollParams) (*GuildPolls, error) {
	row := q.db.QueryRow(ctx, UpdatePoll,
		arg.PollUuid,
		arg.IsSetup,
		arg.HasEnded,
		arg.Title,
		arg.Description,
		arg.AccentColour,
		arg.ImageUrl,
		arg.StartTime,
		arg.EndTime,
		arg.PollOptions,
		arg.IsAnonymous,
		arg.MaximumSelections,
		arg.Resubmissions,
		arg.ResultsVisibility,
		arg.RolesAllowed,
		arg.RolesExcluded,
		arg.MinimumJoinDate,
		arg.MessageID,
		arg.ChannelID,
	)
	var i GuildPolls
	err := row.Scan(
		&i.PollUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.HasEnded,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.PollOptions,
		&i.IsAnonymous,
		&i.MaximumSelections,
		&i.Resubmissions,
		&i.ResultsVisibility,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
	)
	return &i, err
}

const UpdatePollMessage = `-- name: UpdatePollMessage :one
UPDATE
    guild_polls
SET
    message_id = $2,
    channel_id = $3
WHERE
    poll_uuid = $1
RETURNING
    poll_uuid, created_at, guild_id, created_by, has_ended, is_setup, title, description, accent_colour, image_url, start_time, end_time, poll_options, is_anonymous, maximum_selections, resubmissions, results_visibility, roles_allowed, roles_excluded, minimum_join_date, message_id, channel_id
`

type UpdatePollMessageParams struct {
	PollUuid  uuid.UUID `json:"poll_uuid"`
	MessageID int64     `json:"message_id"`
	ChannelID int64     `json:"channel_id"`
}

func (q *Queries) UpdatePollMessage(ctx context.Context, arg UpdatePollMessageParams) (*GuildPolls, error) {
	row := q.db.QueryRow(ctx, UpdatePollMessage, arg.PollUuid, arg.MessageID, arg.ChannelID)
	var i GuildPolls
	err := row.Scan(
		&i.PollUuid,
		&i.CreatedAt,
		&i.GuildID,
		&i.CreatedBy,
		&i.HasEnded,
		&i.IsSetup,
		&i.Title,
		&i.Description,
		&i.AccentColour,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.PollOptions,
		&i.IsAnonymous,
		&i.MaximumSelections,
		&i.Resubmissions,
		&i.ResultsVisibility,
		&i.RolesAllowed,
		&i.RolesExcluded,
		&i.MinimumJoinDate,
		&i.MessageID,
		&i.ChannelID,
	)
	return &i, err
}
