// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_features_query.sql

package database

import (
	"context"
)

const AddGuildFeature = `-- name: AddGuildFeature :exec
INSERT INTO guild_features (guild_id, created_at, feature)
VALUES ($1, NOW(), $2)
ON CONFLICT (guild_id, feature) DO NOTHING
`

type AddGuildFeatureParams struct {
	GuildID int64  `json:"guild_id"`
	Feature string `json:"feature"`
}

func (q *Queries) AddGuildFeature(ctx context.Context, arg AddGuildFeatureParams) error {
	_, err := q.db.Exec(ctx, AddGuildFeature, arg.GuildID, arg.Feature)
	return err
}

const GetGuildFeatures = `-- name: GetGuildFeatures :many
SELECT feature
FROM guild_features
WHERE guild_id = $1
`

func (q *Queries) GetGuildFeatures(ctx context.Context, guildID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, GetGuildFeatures, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var feature string
		if err := rows.Scan(&feature); err != nil {
			return nil, err
		}
		items = append(items, feature)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const HasGuildFeature = `-- name: HasGuildFeature :one
SELECT 1
FROM guild_features
WHERE guild_id = $1 AND feature = $2
`

type HasGuildFeatureParams struct {
	GuildID int64  `json:"guild_id"`
	Feature string `json:"feature"`
}

func (q *Queries) HasGuildFeature(ctx context.Context, arg HasGuildFeatureParams) (int32, error) {
	row := q.db.QueryRow(ctx, HasGuildFeature, arg.GuildID, arg.Feature)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const RemoveGuildFeature = `-- name: RemoveGuildFeature :exec
DELETE FROM guild_features
WHERE guild_id = $1 AND feature = $2
`

type RemoveGuildFeatureParams struct {
	GuildID int64  `json:"guild_id"`
	Feature string `json:"feature"`
}

func (q *Queries) RemoveGuildFeature(ctx context.Context, arg RemoveGuildFeatureParams) error {
	_, err := q.db.Exec(ctx, RemoveGuildFeature, arg.GuildID, arg.Feature)
	return err
}
