// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest_voice_channel_events_schema.sql

package database

import (
	"database/sql"
	"time"
)

type CreateManyIngestVoiceChannelEventsParams struct {
	GuildID    int64         `json:"guild_id"`
	UserID     int64         `json:"user_id"`
	ChannelID  sql.NullInt64 `json:"channel_id"`
	EventType  string        `json:"event_type"`
	OccurredAt time.Time     `json:"occurred_at"`
}
