// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest_message_events_query.sql

package database

import (
	"time"
)

type CreateManyIngestMessageEventsParams struct {
	MessageID  int64     `json:"message_id"`
	GuildID    int64     `json:"guild_id"`
	ChannelID  int64     `json:"channel_id"`
	UserID     int64     `json:"user_id"`
	EventType  string    `json:"event_type"`
	OccurredAt time.Time `json:"occurred_at"`
}
