// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation_checkup_query.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
)

const CreateModerationCheckup = `-- name: CreateModerationCheckup :one
INSERT INTO moderation_checkup (checkup_uuid, guild_id, user_id, data_type, started_at)
VALUES ($1, $2, $3, $4, now())
RETURNING checkup_uuid, guild_id, user_id, data_type, started_at
`

type CreateModerationCheckupParams struct {
	CheckupUuid uuid.UUID `json:"checkup_uuid"`
	GuildID     int64     `json:"guild_id"`
	UserID      int64     `json:"user_id"`
	DataType    int32     `json:"data_type"`
}

type CreateModerationCheckupRow struct {
	CheckupUuid uuid.UUID `json:"checkup_uuid"`
	GuildID     int64     `json:"guild_id"`
	UserID      int64     `json:"user_id"`
	DataType    int32     `json:"data_type"`
	StartedAt   time.Time `json:"started_at"`
}

func (q *Queries) CreateModerationCheckup(ctx context.Context, arg CreateModerationCheckupParams) (*CreateModerationCheckupRow, error) {
	row := q.db.QueryRow(ctx, CreateModerationCheckup,
		arg.CheckupUuid,
		arg.GuildID,
		arg.UserID,
		arg.DataType,
	)
	var i CreateModerationCheckupRow
	err := row.Scan(
		&i.CheckupUuid,
		&i.GuildID,
		&i.UserID,
		&i.DataType,
		&i.StartedAt,
	)
	return &i, err
}

const UpdateModerationCheckup = `-- name: UpdateModerationCheckup :exec
UPDATE moderation_checkup
SET completed_at = now(),
    dom = $2,
    inv = $3,
    score_change = $4,
    score_safe = $5,
    score_question = $6,
    score_explicit = $7,
    is_blocked = $8
WHERE checkup_uuid = $1
`

type UpdateModerationCheckupParams struct {
	CheckupUuid   uuid.UUID       `json:"checkup_uuid"`
	Dom           pgtype.JSONB    `json:"dom"`
	Inv           pgtype.JSONB    `json:"inv"`
	ScoreChange   sql.NullFloat64 `json:"score_change"`
	ScoreSafe     sql.NullFloat64 `json:"score_safe"`
	ScoreQuestion sql.NullFloat64 `json:"score_question"`
	ScoreExplicit sql.NullFloat64 `json:"score_explicit"`
	IsBlocked     sql.NullBool    `json:"is_blocked"`
}

func (q *Queries) UpdateModerationCheckup(ctx context.Context, arg UpdateModerationCheckupParams) error {
	_, err := q.db.Exec(ctx, UpdateModerationCheckup,
		arg.CheckupUuid,
		arg.Dom,
		arg.Inv,
		arg.ScoreChange,
		arg.ScoreSafe,
		arg.ScoreQuestion,
		arg.ScoreExplicit,
		arg.IsBlocked,
	)
	return err
}
