// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation_checkup_queue_query.sql

package database

import (
	"context"

	"github.com/gofrs/uuid"
)

const CreateModerationCheckupQueue = `-- name: CreateModerationCheckupQueue :one
INSERT INTO moderation_checkup_queue (checkup_queue_uuid, guild_id, user_id, audit_type, created_at, value)
VALUES ($1, $2, $3, $4, now(), $5)
RETURNING checkup_queue_uuid, guild_id, user_id, audit_type, created_at, value
`

type CreateModerationCheckupQueueParams struct {
	CheckupQueueUuid uuid.UUID   `json:"checkup_queue_uuid"`
	GuildID          int64       `json:"guild_id"`
	UserID           int64       `json:"user_id"`
	AuditType        int32       `json:"audit_type"`
	Value            interface{} `json:"value"`
}

func (q *Queries) CreateModerationCheckupQueue(ctx context.Context, arg CreateModerationCheckupQueueParams) (*ModerationCheckupQueue, error) {
	row := q.db.QueryRow(ctx, CreateModerationCheckupQueue,
		arg.CheckupQueueUuid,
		arg.GuildID,
		arg.UserID,
		arg.AuditType,
		arg.Value,
	)
	var i ModerationCheckupQueue
	err := row.Scan(
		&i.CheckupQueueUuid,
		&i.GuildID,
		&i.UserID,
		&i.AuditType,
		&i.CreatedAt,
		&i.Value,
	)
	return &i, err
}

const FetchModerationCheckupQueue = `-- name: FetchModerationCheckupQueue :many
SELECT checkup_queue_uuid, guild_id, user_id, audit_type, created_at, value
FROM moderation_checkup_queue
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) FetchModerationCheckupQueue(ctx context.Context, limit int32) ([]*ModerationCheckupQueue, error) {
	rows, err := q.db.Query(ctx, FetchModerationCheckupQueue, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ModerationCheckupQueue{}
	for rows.Next() {
		var i ModerationCheckupQueue
		if err := rows.Scan(
			&i.CheckupQueueUuid,
			&i.GuildID,
			&i.UserID,
			&i.AuditType,
			&i.CreatedAt,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveFromModerationCheckupQueue = `-- name: RemoveFromModerationCheckupQueue :exec
DELETE FROM moderation_checkup_queue
WHERE checkup_queue_uuid IN ($1)
`

func (q *Queries) RemoveFromModerationCheckupQueue(ctx context.Context, checkupQueueUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, RemoveFromModerationCheckupQueue, checkupQueueUuid)
	return err
}
