// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: science_guild_events_query.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
)

type CreateManyScienceGuildEventsParams struct {
	GuildEventUuid uuid.UUID     `json:"guild_event_uuid"`
	GuildID        int64         `json:"guild_id"`
	UserID         sql.NullInt64 `json:"user_id"`
	CreatedAt      time.Time     `json:"created_at"`
	EventType      int32         `json:"event_type"`
	Data           pgtype.JSON   `json:"data"`
}

const CreateScienceGuildEvent = `-- name: CreateScienceGuildEvent :one
INSERT INTO science_guild_events (guild_event_uuid, guild_id, user_id, created_at, event_type, data)
    VALUES (uuid_generate_v7(), $1, $2, now(), $3, $4)
RETURNING
    guild_event_uuid, guild_id, user_id, created_at, event_type, data
`

type CreateScienceGuildEventParams struct {
	GuildID   int64         `json:"guild_id"`
	UserID    sql.NullInt64 `json:"user_id"`
	EventType int32         `json:"event_type"`
	Data      pgtype.JSON   `json:"data"`
}

func (q *Queries) CreateScienceGuildEvent(ctx context.Context, arg CreateScienceGuildEventParams) (*ScienceGuildEvents, error) {
	row := q.db.QueryRow(ctx, CreateScienceGuildEvent,
		arg.GuildID,
		arg.UserID,
		arg.EventType,
		arg.Data,
	)
	var i ScienceGuildEvents
	err := row.Scan(
		&i.GuildEventUuid,
		&i.GuildID,
		&i.UserID,
		&i.CreatedAt,
		&i.EventType,
		&i.Data,
	)
	return &i, err
}

const GetExpiredWelcomeMessageEvents = `-- name: GetExpiredWelcomeMessageEvents :many
SELECT
    science_guild_events.guild_id,
    science_guild_events.user_id,
    CAST(science_guild_events.data ->> 'channel_id' AS BIGINT) AS channel_id,
    CAST(science_guild_events.data ->> 'message_id' AS BIGINT) AS message_id
FROM 
    science_guild_events
    LEFT JOIN
        science_guild_events message_deleted
    ON
        message_deleted.guild_id = science_guild_events.guild_id
        AND message_deleted.user_id = science_guild_events.user_id
        AND message_deleted.event_type = $1
        AND message_deleted.data ->> 'message_id' = science_guild_events.data ->> 'message_id'
        AND message_deleted.created_at > $2
WHERE
    science_guild_events.guild_id = $3
    AND science_guild_events.event_type = $4
    AND science_guild_events.data ->> 'message_id' IS NOT NULL
    AND science_guild_events.created_at < $5
    AND science_guild_events.created_at > $2
    AND message_deleted.guild_event_uuid IS NULL
LIMIT $6
`

type GetExpiredWelcomeMessageEventsParams struct {
	ScienceGuildEventTypeWelcomeMessageRemoved int32     `json:"science_guild_event_type_welcome_message_removed"`
	WelcomeMessageLifetimeLookback             time.Time `json:"welcome_message_lifetime_lookback"`
	GuildID                                    int64     `json:"guild_id"`
	ScienceGuildEventTypeUserWelcomed          int32     `json:"science_guild_event_type_user_welcomed"`
	WelcomeMessageLifetime                     time.Time `json:"welcome_message_lifetime"`
	EventLimit                                 int32     `json:"event_limit"`
}

type GetExpiredWelcomeMessageEventsRow struct {
	GuildID   int64         `json:"guild_id"`
	UserID    sql.NullInt64 `json:"user_id"`
	ChannelID int64         `json:"channel_id"`
	MessageID int64         `json:"message_id"`
}

func (q *Queries) GetExpiredWelcomeMessageEvents(ctx context.Context, arg GetExpiredWelcomeMessageEventsParams) ([]*GetExpiredWelcomeMessageEventsRow, error) {
	rows, err := q.db.Query(ctx, GetExpiredWelcomeMessageEvents,
		arg.ScienceGuildEventTypeWelcomeMessageRemoved,
		arg.WelcomeMessageLifetimeLookback,
		arg.GuildID,
		arg.ScienceGuildEventTypeUserWelcomed,
		arg.WelcomeMessageLifetime,
		arg.EventLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetExpiredWelcomeMessageEventsRow{}
	for rows.Next() {
		var i GetExpiredWelcomeMessageEventsRow
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.ChannelID,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetGuildMemberJoins = `-- name: GetGuildMemberJoins :many
SELECT
    date_trunc($1, science_guild_events.created_at)::TIMESTAMP AS date,
    COUNT(*)::INT AS join_count
FROM
    science_guild_events
WHERE
    science_guild_events.guild_id = $2
    AND science_guild_events.event_type = $3
GROUP BY
    date_trunc($1, science_guild_events.created_at)
ORDER BY
    date_trunc($1, science_guild_events.created_at) ASC
`

type GetGuildMemberJoinsParams struct {
	Period                        string `json:"period"`
	GuildID                       int64  `json:"guild_id"`
	ScienceGuildEventTypeUserJoin int32  `json:"science_guild_event_type_user_join"`
}

type GetGuildMemberJoinsRow struct {
	Date      time.Time `json:"date"`
	JoinCount int32     `json:"join_count"`
}

func (q *Queries) GetGuildMemberJoins(ctx context.Context, arg GetGuildMemberJoinsParams) ([]*GetGuildMemberJoinsRow, error) {
	rows, err := q.db.Query(ctx, GetGuildMemberJoins, arg.Period, arg.GuildID, arg.ScienceGuildEventTypeUserJoin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetGuildMemberJoinsRow{}
	for rows.Next() {
		var i GetGuildMemberJoinsRow
		if err := rows.Scan(&i.Date, &i.JoinCount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetGuildMemberRetention = `-- name: GetGuildMemberRetention :one
WITH joined AS (
    SELECT DISTINCT ON (user_id)
        user_id,
        created_at AS joined_at
    FROM science_guild_events
    WHERE guild_id = $1
        AND science_guild_events.event_type = $3
        AND science_guild_events.created_at BETWEEN $4 AND $5
    ORDER BY user_id, created_at DESC
)

SELECT
    COUNT(*)::int AS members_joined,
    COUNT(*) FILTER (
        WHERE EXISTS (
            SELECT 1
            FROM science_guild_events leave_event
            WHERE leave_event.guild_id = $1
                AND leave_event.user_id = joined.user_id
                AND leave_event.event_type = $2
                AND leave_event.created_at > joined.joined_at
        )
    )::int AS members_left
FROM joined
`

type GetGuildMemberRetentionParams struct {
	GuildID                        int64     `json:"guild_id"`
	ScienceGuildEventTypeUserLeave int32     `json:"science_guild_event_type_user_leave"`
	ScienceGuildEventTypeUserJoin  int32     `json:"science_guild_event_type_user_join"`
	DateFrom                       time.Time `json:"date_from"`
	DateTo                         time.Time `json:"date_to"`
}

type GetGuildMemberRetentionRow struct {
	MembersJoined int32 `json:"members_joined"`
	MembersLeft   int32 `json:"members_left"`
}

func (q *Queries) GetGuildMemberRetention(ctx context.Context, arg GetGuildMemberRetentionParams) (*GetGuildMemberRetentionRow, error) {
	row := q.db.QueryRow(ctx, GetGuildMemberRetention,
		arg.GuildID,
		arg.ScienceGuildEventTypeUserLeave,
		arg.ScienceGuildEventTypeUserJoin,
		arg.DateFrom,
		arg.DateTo,
	)
	var i GetGuildMemberRetentionRow
	err := row.Scan(&i.MembersJoined, &i.MembersLeft)
	return &i, err
}

const GetGuildMemberRetentionMatrix = `-- name: GetGuildMemberRetentionMatrix :many
WITH joined AS (
    SELECT DISTINCT ON (user_id)
        user_id,
        created_at AS joined_at
    FROM science_guild_events
    WHERE science_guild_events.guild_id = $1
        AND science_guild_events.event_type = $2
        AND science_guild_events.created_at BETWEEN (($3)::timestamp - interval '1 year') AND $3
    ORDER BY user_id, created_at DESC
),
left_events AS (
    SELECT DISTINCT ON (user_id)
        user_id,
        created_at AS left_at
    FROM science_guild_events
    WHERE science_guild_events.guild_id = $1
        AND science_guild_events.event_type = $4
        AND science_guild_events.created_at BETWEEN (($3)::timestamp - interval '1 year') AND $3
    ORDER BY user_id, created_at DESC
),
cohorts AS (
    SELECT
        (DATE_PART('year', age($3::timestamp, joined.joined_at)) * 12 + DATE_PART('month', age($3::timestamp, joined.joined_at)))::int AS joined_months_ago,
        (DATE_PART('year', age($3::timestamp, left_events.left_at)) * 12 + DATE_PART('month', age($3::timestamp, left_events.left_at)))::int AS left_months_ago
    FROM joined
        LEFT JOIN left_events ON left_events.user_id = joined.user_id
            AND left_events.left_at > joined.joined_at
)

SELECT
    joined_months_ago,
    COALESCE(left_months_ago, -1) AS left_months_ago,
    COUNT(*)::int AS member_count
FROM cohorts
WHERE joined_months_ago BETWEEN 0 AND 12
    AND (left_months_ago IS NULL OR left_months_ago BETWEEN 0 AND 12)
GROUP BY joined_months_ago, left_months_ago
ORDER BY joined_months_ago, left_months_ago
`

type GetGuildMemberRetentionMatrixParams struct {
	GuildID                        int64     `json:"guild_id"`
	ScienceGuildEventTypeUserJoin  int32     `json:"science_guild_event_type_user_join"`
	DateTo                         time.Time `json:"date_to"`
	ScienceGuildEventTypeUserLeave int32     `json:"science_guild_event_type_user_leave"`
}

type GetGuildMemberRetentionMatrixRow struct {
	JoinedMonthsAgo int32 `json:"joined_months_ago"`
	LeftMonthsAgo   int32 `json:"left_months_ago"`
	MemberCount     int32 `json:"member_count"`
}

// Returns, for members who joined within [date_to - 1 year, date_to], how many months ago they
// joined (X axis) and how many months ago they left (Y axis), 0 being the current month.
// Members who have not left are included with a NULL left_months_ago.
func (q *Queries) GetGuildMemberRetentionMatrix(ctx context.Context, arg GetGuildMemberRetentionMatrixParams) ([]*GetGuildMemberRetentionMatrixRow, error) {
	rows, err := q.db.Query(ctx, GetGuildMemberRetentionMatrix,
		arg.GuildID,
		arg.ScienceGuildEventTypeUserJoin,
		arg.DateTo,
		arg.ScienceGuildEventTypeUserLeave,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetGuildMemberRetentionMatrixRow{}
	for rows.Next() {
		var i GetGuildMemberRetentionMatrixRow
		if err := rows.Scan(&i.JoinedMonthsAgo, &i.LeftMonthsAgo, &i.MemberCount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetLeftGuildMemberDaysOnServer = `-- name: GetLeftGuildMemberDaysOnServer :many
WITH joined AS (
    SELECT DISTINCT ON (user_id)
        user_id,
        created_at AS joined_at
    FROM science_guild_events
    WHERE science_guild_events.guild_id = $1
        AND science_guild_events.event_type = $2
        AND science_guild_events.created_at BETWEEN $3 AND $4
    ORDER BY science_guild_events.user_id, created_at DESC
),
left_events AS (
    SELECT DISTINCT ON (user_id)
        user_id,
        created_at AS left_at
    FROM science_guild_events
    WHERE science_guild_events.guild_id = $1
        AND science_guild_events.event_type = $5
        AND science_guild_events.created_at >= $3
    ORDER BY science_guild_events.user_id, created_at DESC
)

SELECT
    COUNT(*)::int AS count,
    CASE WHEN left_events.left_at IS NULL THEN
        (EXTRACT(EPOCH FROM now() - joined.joined_at) / 86400)
    ELSE
        EXTRACT(EPOCH FROM COALESCE(left_events.left_at, now()) - joined.joined_at) / 86400
    END::int AS days_on_server
FROM joined
    LEFT JOIN left_events ON left_events.user_id = joined.user_id
GROUP BY days_on_server
ORDER BY days_on_server DESC
`

type GetLeftGuildMemberDaysOnServerParams struct {
	GuildID                        int64     `json:"guild_id"`
	ScienceGuildEventTypeUserJoin  int32     `json:"science_guild_event_type_user_join"`
	DateFrom                       time.Time `json:"date_from"`
	DateTo                         time.Time `json:"date_to"`
	ScienceGuildEventTypeUserLeave int32     `json:"science_guild_event_type_user_leave"`
}

type GetLeftGuildMemberDaysOnServerRow struct {
	Count        int32 `json:"count"`
	DaysOnServer int32 `json:"days_on_server"`
}

func (q *Queries) GetLeftGuildMemberDaysOnServer(ctx context.Context, arg GetLeftGuildMemberDaysOnServerParams) ([]*GetLeftGuildMemberDaysOnServerRow, error) {
	rows, err := q.db.Query(ctx, GetLeftGuildMemberDaysOnServer,
		arg.GuildID,
		arg.ScienceGuildEventTypeUserJoin,
		arg.DateFrom,
		arg.DateTo,
		arg.ScienceGuildEventTypeUserLeave,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetLeftGuildMemberDaysOnServerRow{}
	for rows.Next() {
		var i GetLeftGuildMemberDaysOnServerRow
		if err := rows.Scan(&i.Count, &i.DaysOnServer); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetScienceGuildEvent = `-- name: GetScienceGuildEvent :one
SELECT
    guild_event_uuid, guild_id, user_id, created_at, event_type, data
FROM
    science_guild_events
WHERE
    guild_event_uuid = $1
`

func (q *Queries) GetScienceGuildEvent(ctx context.Context, guildEventUuid uuid.UUID) (*ScienceGuildEvents, error) {
	row := q.db.QueryRow(ctx, GetScienceGuildEvent, guildEventUuid)
	var i ScienceGuildEvents
	err := row.Scan(
		&i.GuildEventUuid,
		&i.GuildID,
		&i.UserID,
		&i.CreatedAt,
		&i.EventType,
		&i.Data,
	)
	return &i, err
}

const GetScienceGuildEventsForGuild = `-- name: GetScienceGuildEventsForGuild :many
SELECT DISTINCT
    science_guild_events.user_id,
    science_guild_events.event_type,
    science_guild_events.created_at
FROM
    science_guild_events
WHERE
    science_guild_events.guild_id = $1
    AND science_guild_events.event_type = $2
    AND science_guild_events.created_at BETWEEN $3 AND $4
`

type GetScienceGuildEventsForGuildParams struct {
	GuildID   int64     `json:"guild_id"`
	EventType int32     `json:"event_type"`
	DateFrom  time.Time `json:"date_from"`
	DateTo    time.Time `json:"date_to"`
}

type GetScienceGuildEventsForGuildRow struct {
	UserID    sql.NullInt64 `json:"user_id"`
	EventType int32         `json:"event_type"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) GetScienceGuildEventsForGuild(ctx context.Context, arg GetScienceGuildEventsForGuildParams) ([]*GetScienceGuildEventsForGuildRow, error) {
	rows, err := q.db.Query(ctx, GetScienceGuildEventsForGuild,
		arg.GuildID,
		arg.EventType,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetScienceGuildEventsForGuildRow{}
	for rows.Next() {
		var i GetScienceGuildEventsForGuildRow
		if err := rows.Scan(&i.UserID, &i.EventType, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetScienceGuildEventsForGuildGroupedByPeriod = `-- name: GetScienceGuildEventsForGuildGroupedByPeriod :many
SELECT
    date_trunc($1, science_guild_events.created_at)::TIMESTAMP AS date,
    COUNT(*)::INT AS event_count
FROM
    science_guild_events
WHERE
    science_guild_events.guild_id = $2
    AND science_guild_events.event_type = $3
    AND science_guild_events.created_at BETWEEN $4 AND $5
GROUP BY
    date_trunc($1, science_guild_events.created_at)
ORDER BY
    date_trunc($1, science_guild_events.created_at) ASC
`

type GetScienceGuildEventsForGuildGroupedByPeriodParams struct {
	Period    string    `json:"period"`
	GuildID   int64     `json:"guild_id"`
	EventType int32     `json:"event_type"`
	DateFrom  time.Time `json:"date_from"`
	DateTo    time.Time `json:"date_to"`
}

type GetScienceGuildEventsForGuildGroupedByPeriodRow struct {
	Date       time.Time `json:"date"`
	EventCount int32     `json:"event_count"`
}

func (q *Queries) GetScienceGuildEventsForGuildGroupedByPeriod(ctx context.Context, arg GetScienceGuildEventsForGuildGroupedByPeriodParams) ([]*GetScienceGuildEventsForGuildGroupedByPeriodRow, error) {
	rows, err := q.db.Query(ctx, GetScienceGuildEventsForGuildGroupedByPeriod,
		arg.Period,
		arg.GuildID,
		arg.EventType,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetScienceGuildEventsForGuildGroupedByPeriodRow{}
	for rows.Next() {
		var i GetScienceGuildEventsForGuildGroupedByPeriodRow
		if err := rows.Scan(&i.Date, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetScienceGuildJoinLeaveEventForUser = `-- name: GetScienceGuildJoinLeaveEventForUser :one
SELECT
    guild_event_uuid, science_guild_events.guild_id, user_id, science_guild_events.created_at, event_type, data, invite_code, guild_invites.guild_id, created_by, guild_invites.created_at, uses
FROM
    science_guild_events
    LEFT JOIN guild_invites ON guild_invites.invite_code = science_guild_events.data ->> 'invite_code'
WHERE
    science_guild_events.event_type IN ($1, $2)
    AND science_guild_events.guild_id = $3
    AND science_guild_events.user_id = $4
ORDER BY
    science_guild_events.created_at DESC
LIMIT 1
`

type GetScienceGuildJoinLeaveEventForUserParams struct {
	EventType   int32         `json:"event_type"`
	EventType_2 int32         `json:"event_type_2"`
	GuildID     int64         `json:"guild_id"`
	UserID      sql.NullInt64 `json:"user_id"`
}

type GetScienceGuildJoinLeaveEventForUserRow struct {
	GuildEventUuid uuid.UUID      `json:"guild_event_uuid"`
	GuildID        int64          `json:"guild_id"`
	UserID         sql.NullInt64  `json:"user_id"`
	CreatedAt      time.Time      `json:"created_at"`
	EventType      int32          `json:"event_type"`
	Data           pgtype.JSON    `json:"data"`
	InviteCode     sql.NullString `json:"invite_code"`
	GuildID_2      sql.NullInt64  `json:"guild_id_2"`
	CreatedBy      sql.NullInt64  `json:"created_by"`
	CreatedAt_2    sql.NullTime   `json:"created_at_2"`
	Uses           sql.NullInt64  `json:"uses"`
}

func (q *Queries) GetScienceGuildJoinLeaveEventForUser(ctx context.Context, arg GetScienceGuildJoinLeaveEventForUserParams) (*GetScienceGuildJoinLeaveEventForUserRow, error) {
	row := q.db.QueryRow(ctx, GetScienceGuildJoinLeaveEventForUser,
		arg.EventType,
		arg.EventType_2,
		arg.GuildID,
		arg.UserID,
	)
	var i GetScienceGuildJoinLeaveEventForUserRow
	err := row.Scan(
		&i.GuildEventUuid,
		&i.GuildID,
		&i.UserID,
		&i.CreatedAt,
		&i.EventType,
		&i.Data,
		&i.InviteCode,
		&i.GuildID_2,
		&i.CreatedBy,
		&i.CreatedAt_2,
		&i.Uses,
	)
	return &i, err
}

const SumScienceGuildEventsForGuild = `-- name: SumScienceGuildEventsForGuild :one
SELECT
    COUNT(*)::INT AS event_count
FROM
    science_guild_events
WHERE
    science_guild_events.guild_id = $1
    AND science_guild_events.event_type = $2
    AND science_guild_events.created_at BETWEEN $3 AND $4
`

type SumScienceGuildEventsForGuildParams struct {
	GuildID   int64     `json:"guild_id"`
	EventType int32     `json:"event_type"`
	DateFrom  time.Time `json:"date_from"`
	DateTo    time.Time `json:"date_to"`
}

func (q *Queries) SumScienceGuildEventsForGuild(ctx context.Context, arg SumScienceGuildEventsForGuildParams) (int32, error) {
	row := q.db.QueryRow(ctx, SumScienceGuildEventsForGuild,
		arg.GuildID,
		arg.EventType,
		arg.DateFrom,
		arg.DateTo,
	)
	var event_count int32
	err := row.Scan(&event_count)
	return event_count, err
}
