// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: welcomer_builder_artifacts_query.sql

package database

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const CreateWelcomerBuilderArtifacts = `-- name: CreateWelcomerBuilderArtifacts :one
INSERT INTO welcomer_builder_artifacts (artifact_uuid, guild_id, user_id, created_at, image_type, data, reference)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    artifact_uuid, reference, guild_id, user_id, created_at, image_type, data
`

type CreateWelcomerBuilderArtifactsParams struct {
	ArtifactUuid uuid.UUID `json:"artifact_uuid"`
	GuildID      int64     `json:"guild_id"`
	UserID       int64     `json:"user_id"`
	CreatedAt    time.Time `json:"created_at"`
	ImageType    string    `json:"image_type"`
	Data         []byte    `json:"data"`
	Reference    string    `json:"reference"`
}

func (q *Queries) CreateWelcomerBuilderArtifacts(ctx context.Context, arg CreateWelcomerBuilderArtifactsParams) (*WelcomerBuilderArtifacts, error) {
	row := q.db.QueryRow(ctx, CreateWelcomerBuilderArtifacts,
		arg.ArtifactUuid,
		arg.GuildID,
		arg.UserID,
		arg.CreatedAt,
		arg.ImageType,
		arg.Data,
		arg.Reference,
	)
	var i WelcomerBuilderArtifacts
	err := row.Scan(
		&i.ArtifactUuid,
		&i.Reference,
		&i.GuildID,
		&i.UserID,
		&i.CreatedAt,
		&i.ImageType,
		&i.Data,
	)
	return &i, err
}

const GetMinimalWelcomerBuilderArtifactByGuildId = `-- name: GetMinimalWelcomerBuilderArtifactByGuildId :many
SELECT
    artifact_uuid, reference
FROM
    welcomer_builder_artifacts
WHERE
    guild_id = $1
`

type GetMinimalWelcomerBuilderArtifactByGuildIdRow struct {
	ArtifactUuid uuid.UUID `json:"artifact_uuid"`
	Reference    string    `json:"reference"`
}

func (q *Queries) GetMinimalWelcomerBuilderArtifactByGuildId(ctx context.Context, guildID int64) ([]*GetMinimalWelcomerBuilderArtifactByGuildIdRow, error) {
	rows, err := q.db.Query(ctx, GetMinimalWelcomerBuilderArtifactByGuildId, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetMinimalWelcomerBuilderArtifactByGuildIdRow{}
	for rows.Next() {
		var i GetMinimalWelcomerBuilderArtifactByGuildIdRow
		if err := rows.Scan(&i.ArtifactUuid, &i.Reference); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetWelcomerBuilderArtifactByArtifactUUID = `-- name: GetWelcomerBuilderArtifactByArtifactUUID :one
SELECT
    artifact_uuid, reference, guild_id, user_id, created_at, image_type, data
FROM
    welcomer_builder_artifacts
WHERE
    artifact_uuid = $1
`

func (q *Queries) GetWelcomerBuilderArtifactByArtifactUUID(ctx context.Context, artifactUuid uuid.UUID) (*WelcomerBuilderArtifacts, error) {
	row := q.db.QueryRow(ctx, GetWelcomerBuilderArtifactByArtifactUUID, artifactUuid)
	var i WelcomerBuilderArtifacts
	err := row.Scan(
		&i.ArtifactUuid,
		&i.Reference,
		&i.GuildID,
		&i.UserID,
		&i.CreatedAt,
		&i.ImageType,
		&i.Data,
	)
	return &i, err
}

const GetWelcomerBuilderArtifactsByGuildId = `-- name: GetWelcomerBuilderArtifactsByGuildId :many
SELECT
    artifact_uuid, reference, guild_id, user_id, created_at, image_type, data
FROM
    welcomer_builder_artifacts
WHERE
    guild_id = $1
`

func (q *Queries) GetWelcomerBuilderArtifactsByGuildId(ctx context.Context, guildID int64) ([]*WelcomerBuilderArtifacts, error) {
	rows, err := q.db.Query(ctx, GetWelcomerBuilderArtifactsByGuildId, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*WelcomerBuilderArtifacts{}
	for rows.Next() {
		var i WelcomerBuilderArtifacts
		if err := rows.Scan(
			&i.ArtifactUuid,
			&i.Reference,
			&i.GuildID,
			&i.UserID,
			&i.CreatedAt,
			&i.ImageType,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveWelcomerArtifactsByReference = `-- name: RemoveWelcomerArtifactsByReference :execrows
DELETE FROM welcomer_builder_artifacts
WHERE
    reference = ANY($2::string[])
    AND guild_id = $1
`

type RemoveWelcomerArtifactsByReferenceParams struct {
	GuildID int64    `json:"guild_id"`
	Refs    []string `json:"refs"`
}

func (q *Queries) RemoveWelcomerArtifactsByReference(ctx context.Context, arg RemoveWelcomerArtifactsByReferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, RemoveWelcomerArtifactsByReference, arg.GuildID, arg.Refs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
